geodynamics/Rayleigh

CONTRIBUTING.md
README.md

As discussed this is a proposal for a CONTRIBUTING.md document, as recommended by Github (https://help.github.com/articles/setting-guidelines-for-repository-contributors/). It should give users an idea about how they can contribute to Rayleigh (and encourage them to do so). We can discuss the individual parts of this file if you prefer a different wording or a different policy altogether, the current version is mostly taken from the geodynamics/aspect repository and might not be entirely applicable to Rayleigh. Let me know what you think about it.

Add contributing md

---

CONTRIBUTING.md

Fixes some remaining typos in #10.

Update Contributing.md, fix link

---

doc/src/user_guide/running.tex

Fixed a typo in documentation

---

src/Physics/Sphere_Hybrid_Space.F90

Nothing of any kind of relevance at all. Just trying out the reviewing process :-)

Be more uniform in the commenting style.

---

docker/rayleigh-buildenv-bionic/Dockerfile
docker/rayleigh-buildenv-bionic/README.md
docker/rayleigh/Dockerfile
docker/rayleigh/README.md

Once set up, the DockerHub autobuilt containers will be on the [Geodynamics DockerHub](https://hub.docker.com/u/geodynamics/) page
Credit to @gassmoeller for the Dockerfiles

Add Dockerfiles for DockerHub autobuilt containers

---

Jenkinsfile

Switch to DockerHub autobuilt container for buildenv

---

src/Physics/Checkpointing.F90

Added a few comments to checkpoints.F90 that describe what is being done during the checkpoint reading.

Additional Comments in Checkpointing.F90

---

src/Diagnostics/Diagnostics_Vorticity_Field.F90
src/Diagnostics/Verifications/kinetic_helicity/main_input
src/Diagnostics/Verifications/kinetic_helicity/test_helicity_components.py
src/Diagnostics/vorticity_field_codes.F

The various components of the kinetic helicity have been added and tested/verified. The input file and plotting routine that were used to verify the diagnostics are in a new directory in Diagnostics/Verifications/

Kinetic helicity diagnostics and new Verifications directory

---

doc/src/user_guide/Rayleigh_User_Guide.tex
doc/src/user_guide/checkpointing.tex
doc/src/user_guide/cookbooks.tex
doc/src/user_guide/running.tex

Added cookbooks section to User Guide. This update is for the four main_input files for the four *_minimal benchmarks. Also added labels to a few other *.tex sections for reference in the new cookbooks.tex file.

added cookbooks and updated labels

---

doc/src/user_guide/physics.tex

Added a new section label in physics.tex.

added a new section label

---

doc/src/user_guide/Rayleigh_User_Guide.tex

This corrects my original pull request #78 which I closed.
This change corrects my hack to the template to get the title correct and now uses the suggested method.
Please note that  this is committed to my master - whoops :( . Sigh.

Implements the cover page title correctly ... again.

---

src/Diagnostics/amom_equation_codes.F
src/Diagnostics/current_density_codes.F
src/Diagnostics/induction_equation_codes.F
src/Diagnostics/ke_equation_codes.F
src/Diagnostics/kinetic_energy_codes.F
src/Diagnostics/magnetic_energy_codes.F
src/Diagnostics/magnetic_field_codes.F
src/Diagnostics/mass_flux_codes.F
src/Diagnostics/me_equation_codes.F
src/Diagnostics/momentum_equation_codes.F
src/Diagnostics/thermal_energy_codes.F
src/Diagnostics/thermal_equation_codes.F
src/Diagnostics/thermal_field_codes.F
src/Diagnostics/velocity_field_codes.F
src/Diagnostics/vorticity_field_codes.F
src/Include/indices.F

This adds the license header to all files that have not been covered in #57.

Add license header to all .F files

---

src/Math_Layer/Theta_Derivatives.F90

By default, the compiler flags consider lines up to 132 characters. One of the lines in this file violates this, so break it.

Break a couple of very long lines.

---

dev_build
src/IO/Spherical_IO.F90
src/Physics/Input.F90

Having added a few command-line parameters over the past week, I noticed that the semantics of doing so was cumbersome.  I've added a new interface named read_cmd_line which allows any new command-line parameters to be added by creating a single line of new code in Input.F90.   I've tested the functionality of the interface, but it might good for a second set of eyes to make sure I didn't misspell any of the preexisting parameter names.
-Nick

Read_CMD_Line

---

Jenkinsfile

Kubernetes ended up not working for our Jenkins server, so we switched to direct Docker containers. The Jenkinsfile should still otherwise work, though.

Change Jenkinsfile from Kubernetes to Docker

---

doc/source/User_Guide/overview.rst

Rearranges Overview and adds an Acknowledging and Referencing section. Nick has done a quick read through already.

Adds attributions to the Overview

---

doc/source/Rayleigh_Output_Variables.rst
doc/source/conf.py
doc/source/index.rst
doc/source/stream.rst
doc/source/vids.rst

This PR fixes some style issues with the pdf documentation and removes some now not longer needed sections without contents.

Prettify pdf and html documentation

---

Makefile
docker/rayleigh-buildenv-bionic/Dockerfile
etc/check_ipynb_cleared

This fixes a few error messages and includes `nbstripout` into the CI Docker container.

improve nbstripout integration

---

.gitignore
CONTRIBUTING.md
doc/source/User_Guide/installation.rst

This explains how to use `make fdeps` and the parallel make. Please comment if it is understandable.

Document process to update Fortran dependencies

---

doc/source/vids.rst

Reformats video gallery for online documentation.
Videos are tiled 3 across and uses the raw html 'embed' YouTube formatting.
This ties @bangerth in the number of commits ...

Reformats video gallery

---

doc/source/Rayleigh_Output_Variables.rst
doc/source/User_Guide/index.rst
doc/source/index.rst

As discussed with @ljhwang this improves the order of sections and renames the label of one section to fit on the webpage.

Elevate chapters in documentation

---

CONTRIBUTING.md

The mailing list does not exist anymore.

mention the forum instead of the mailing list

---

doc/requirements.txt

This adds numpy to readthedocs.

Add dependencies for readthedocs

---

doc/source/publications/author_plot.R

I made a boo boo in the comment field in the .R file.  This is now corrected.

Corrects an error in the comments.

---

post_processing/YT_volrender_tutorial1.ipynb
post_processing/YT_volrender_tutorial2.ipynb

Added two new notebooks for playing around with volume rendering in YT. Comments in the notebook indicate where there are still issues with YT capabilities that need to be sorted out.
-Tutorial1 provides an overview
-Tutorial2 shows some additional examples and shows how to convert from Spherical quantities to Cartesian quantities within Python.

added python notebooks for volume rendering with YT

---

post_processing/YT_volrender_tutorial1.ipynb

We had a broken test, this should fix it.

Remove output field

---

doc/source/User_Guide/benchmarking.rst
doc/source/User_Guide/checkpointing.rst
doc/source/User_Guide/cookbooks.rst
doc/source/User_Guide/custom_reference_states.rst
doc/source/User_Guide/diagnostics.rst
doc/source/User_Guide/ensemble_mode.rst
doc/source/User_Guide/installation.rst
doc/source/User_Guide/io_redirection.rst
doc/source/User_Guide/overview.rst
doc/source/User_Guide/physics.rst
doc/source/User_Guide/running.rst
doc/source/diagnostic_values/Rayleigh_Output_Variables.rst
doc/source/diagnostic_values/index.rst

Fixes bad links to sections and other bad links.  Required updating all files using :sec: 
And fixed a few other random errors.

Fixes section links

---

README.md

Fix filename

---

doc/source/diagnostic_values/Rayleigh_Output_Variables.rst

I corrected two constants appearing in the documentation for the Boussinesq momentum equation.

Corrected two constants in Boussinesq equations

---

CONTRIBUTING.md
INSTALL

Add some instructions for how to compile the documentation.

Add instructions for compiling the documentation

---

post_processing/kyle_interp/Makefile
post_processing/kyle_interp/Makefile.gfortran
post_processing/kyle_interp/convert_vdf.bsh
post_processing/kyle_interp/driver.f90
post_processing/kyle_interp/input
post_processing/kyle_interp/interp.bsh
post_processing/kyle_interp/interp.f90
post_processing/kyle_interp/interpolation.f90

Included a new directory with Kyle's parallel interpolation code (with input and Makefiles) to interpolate Spherical_3D quantities onto a Cartesian grid. I can confirm that these compile and work as expected to generate the 'cubed' output files for use with visualizations.

added new directory with code for cartesian interpolation

---

doc/source/User_Guide/custom_reference_states.rst
doc/source/diagnostic_values/Rayleigh_Output_Variables.rst

This is an initial stab at documentation of the custom reference state.   I'm open to fixing typos or inaccuracies, but this section will probably ultimately need a second read/write through by someone else.   Note that I modified the output variable file as well, but only to add a section label.
-Nick

Custom Reference State Documentation

---

post_processing/rayleigh_diagnostics.py

This ACTUALLY fixes the issue from the previous pull request.  Uploaded the wrong (same copy) of rayleigh_diagnostics on accident.   The previous PR just updated a version number in a notebook file.  Oops!

Actually fixed G_Avgs issue in Compile_GlobalAvgs

---

post_processing/rayleigh_diagnostics.py

As with the previous two PRs, this pull request updates one of the time-averaging routines(TimeAvg_AZAverages) such that the class names used are up-to-date with the current (and permanent) class names.

TimeAvg_AZAverages updated to use proper AZ_Avgs class name.

---

doc/source/diagnostic_values/Rayleigh_Output_Variables.rst

This pull request clarifies several points in the "Equation Sets Solved by Rayleigh" section of the documentation. Specifically, it addresses the non-dimensionalization of reference_type=1,3, as well has the relationship of various functions/constants to the heating and transport coefficients. Also the documentation has been reformatted so as to not require a horizontal scroll bar.

Fixed equation set fresh

---

src/Diagnostics/Diagnostics_Thermal_Equation.F90

Fix Some Diagnostic Typos

---

doc/source/User_Guide/checkpointing.rst
post_processing/rayleigh_diagnostics.py
post_processing/vapor_converter.ipynb

- fixed two small typos in checkpointing.rst
- fixed a bug in rayleigh_diagnostics.py where cleanup would fail when converting only vector quantities to vapor input.
- added a more usable but less detailed version of vapor_notebook.ipynb called vapor_converter.ipynb.

typos, bug fix, new vapor converter notebook

---

.github/workflows/linux.yml
docker/rayleigh-buildenv-bionic/Dockerfile
docker/rayleigh-buildenv-focal/Dockerfile

I added a github workflow that uses github actions to mimic the existing testing workflow with Jenkins.

[WIP] Add a GitHub action to test Rayleigh

---

.github/workflows/linux.yml

Do not merge yet, I need to make sure the action succeeds and can be merged.

Fix Github Action

---

README.md

The previous link wasn't working anymore.

update link to qcode docs

---

post_processing/rayleigh_diagnostics.py

The Power_Spectrum class referenced the wrong magnetic field quantity codes. I updated these, fixes Issue #260

Fix Issue #260: typo in rayleigh_diagnostics.py

---

VERSION
configure
input_examples/README

This removes some more duplicated version numbers, and reformats the VERSION file, so that it can be easily used in scripts (the only content of the file is the number now).

Remove duplicated version numbers

---

doc/source/User_Guide/devel_environment.rst
environment.yml
environment_mac.yml

Simplify the online documentation for the development environment using the environment files. Also add a basemap package needed for the some postprocessing examples (https://rayleigh-documentation.readthedocs.io/en/latest/post_processing/Diagnostic_Plotting.html#II.-Configuring-Your-Python-Environment).

Update online documentation for conda environment

---

doc/source/User_Guide/overview.rst

This updates the documentation to include the appropriate citation for Rayleigh 1.0.

Citation Update

---

CHANGELOG.md
README.md
doc/source/User_Guide/overview.rst

Wrapping wrapping last-minute changes related to the DOI and the documentation from release branch 1.0.1 into the main branch.

Rayleigh 1.0.1

---

doc/source/User_Guide/boundary_conditions.rst
doc/source/User_Guide/grid_specification.rst
doc/source/User_Guide/index.rst
doc/source/User_Guide/initial_conditions.rst
doc/source/User_Guide/timing_control.rst

This adds documentation placeholder files and entries in the table of contents for upcoming documentation work.
Under-construction status is noted.
I am merging this without review as discussed in developer meeting.

Added  stub files for new documentation sections

---

.github/workflows/main.yml
CHANGELOG.md
src/Makefile.fdeps
src/Physics/Main.F90
src/Test_Suite/TestSuite.F90
src/Test_Suite/Test_SHT.F90
tests/unit_tests/SHT/expected_output.out
tests/unit_tests/SHT/main_input

This PR includes some unit tests and includes them in the github actions. There are a few tests for the Legendre transform and one test that does the full SHT by including LT, FFT, and transposes.

Add some unit tests

---

configure

The outdated version number in the configure file (line 458) was changed from v0.9.0 to v0.9.5

Changed version number in configure file to 0.9.5

---

configure

Fixing version number in configure file

---

.github/workflows/black.yml
post_processing/pyproject.toml
post_processing/rayleigh.py
post_processing/setup.cfg

This implements a new, more object-oriented Python interface to the outputs. Arrays are loaded using memory mapping if possible.

a new Python interface for outputs

---

.github/workflows/main.yml
conf.py
docker/rayleigh-buildenv-bionic/Dockerfile
environment.yml
environment_doc.yml

Remade version of #373 to trigger the readthedocs build for this PR. I will need to play around with some options, so I will keep this as work in progress for now.

Switch Sphinx theme.

---

doc/source/Namelist_Definitions/Namelist_Variables.rst
doc/source/User_Guide/index.rst
doc/source/diagnostic_codes/qcodes.rst

A suggestion for a renaming of two of the top level section to make their purpose more clear.

Rename and clarify input and output sections.

---

src/Math_Layer/Chebyshev_Polynomials.F90

The radial derivative routine typically computes and stores derivatives within the same buffer.  
If v_r is stored in input buffer(:,:,:,ind), for instance, then dvrdr would be stored in  input buffer(:,:,:,dind).
This add an out of buffer routine, so that now dvdr is stored in another buffer, obuffer(:,:,:)

Out-of-Buffer Chebyshev Derivative Routine

---

.github/workflows/main.yml
post_processing/convert_full3d_to_nc.py
post_processing/convert_full3d_to_vtu.py
pre_processing/rayleigh_spectral_input.py
tests/generic_input/run_test.sh
tests/generic_input/test_output.py

This updates our workflow to a new container image. The old workflow used an image in @gassmoeller's namespace on Docker Hub. For testing I switched this to an image in my namespace. Should we use the geodynamics namespace in the long run? I've seen that Github also offers a container registry, so that might be another option. Any ideas?

switch github workflow to new container using Ubuntu Jammy

---

doc/source/User_Guide/analyze_output.rst
doc/source/User_Guide/getting_started.rst

Reviewed Getting Started with Nick F.

Modified gettingstarted

---

doc/source/User_Guide/physics_math_overview.rst

Doc update

---

doc/source/User_Guide/analyze_output.rst
post_processing/Diagnostic_Plotting.ipynb

Note that there is an issue with the menu related to the Jupyter notebook we are importing.

Reviewed the plotting section

---

doc/source/User_Guide/contribute.rst
doc/source/User_Guide/getting_started.rst
doc/source/User_Guide/index.rst
doc/source/User_Guide/model_setup.rst
doc/source/User_Guide/run_rayleigh.rst

We did not delete the old user manual files, but they are not referenced. Information has been copied over to the new files.

Deploy the new user guide and associated revisions

---

doc/source/User_Guide/analyze_output.rst

Added an embedded YouTube video of Nick Featherstone walking through how to get Rayleigh data into VAPoR.

Added video on VAPoR visualization

---

doc/source/User_Guide/troubleshooting.rst

This should be a more useful support page :smirk:

Improve support page

---

doc/source/User_Guide/physics_math_overview.rst

I think this small change in language is better/clearer.  It feels odd to refer to 'equation sets.'

Small Section Rewording

---

doc/source/User_Guide/physics_math_overview.rst

This PR fills in the streamfunction section of the documentation, which is presently empty.

Description of Streamfunction Approach

---

src/Physics/PDE_Coefficients.F90

There should be no functional change to the code -- just added some comments and reordered/regrouped some of the initialization commands.

Tidy up initialization block of the PDE_Coefficients file

---

doc/source/User_Guide/model_setup.rst

Fixes the spelling of quantities in a few places

Fix a few typos

---

doc/source/citing_rayleigh.rst

Added the current grant number for CIG.

Updated Acknowledging

---

README.md

I removed a space that should not be there.

Removed an unnecessary space.

---

.github/workflows/docker.yml
README.md

The automatic docker build stopped working, because I forgot to update the reference to the master branch. I found one other place where this is referenced as well. Should be all fixed now.

Fix some references to the master branch

---

post_processing/spectral_utils_tutorial.ipynb

Provides examples of spherical harmonic transforms, Chebyshev transforms, d/dr, d/dtheta, and d/dphi derivatives in physical and spectral space using the methods in spectral_utils.py.

Added tutorial jupyter notebook for spectral_utils.py

---

doc/source/citing_rayleigh.rst

As discussed at the last hackathon, we would like to add publishing recommendations to the manuals.
This is the initial pull request.  Note that I did not build the documentation or check the rst (vscode extension was working).  
Please feel free to modify and edit.  
Thanks.

Adds publishing recommendations to documentation

---

src/Physics/Initial_Conditions.F90
src/Physics/PDE_Coefficients.F90

Removed two debugging print statements from PDE_Coefficients.F90.
Removed comment "!Nick" from Initial_Conditions.F90
This just removes some unnecessary prints and comments.  I am merging without review.

Code Cleanup for recent PRs

---

CHANGELOG.md

Changelog updated through PR 494.
Do not merge yet please.

Changelog now up-to-date through May 8, 2024

---

index.rst

The finite difference approximation was not mentioned in the documentation. I added it.

Mention FD

---

doc/source/image_gallery.rst
doc/source/research_enabled_by_rayleigh.rst

Created new page in the documentation in place to put images later on.

[WIP] Add image gallery page to documentation

---

conf.py
doc/source/publications/all.bib
doc/source/publications/publications.rst
doc/source/publications/publications2016.bib
doc/source/publications/publications2018.bib
doc/source/publications/publications2019.bib
doc/source/publications/publications2020.bib
doc/source/publications/publications2021.bib
doc/source/publications/publications2022.bib
doc/source/publications/publications2023.bib
doc/source/publications/software.bib

Updated publications section of documentation

Improve documentation

---

post_processing/rayleigh_diagnostics.py

Added a function in rayleigh_diagnostics.py file to read in the checkpoint files

Added checkpoint reader in rayleigh_diagnostics

---

doc/source/User_Guide/physics_math_overview.rst

Similar to the (formerly) missing c_5 in the viscous heating.

Fairly certain there's a missing c_7 in ohmic heating

---

CHANGELOG.md

edited the changelog for pull request 535

edited changelog

---

doc/source/User_Guide/under_development.rst

Adds the equation set solved by the pseudo-incompressible approximation to the Rayleigh documentation. This information appears in the Under Development Section.

Added documentation for the pseudo-incompressible approximation

---

doc/source/User_Guide/model_setup.rst

Fixes formatting of code blocks and tables.

documentation fixes
