Makefile, configure
I added the --with-custom= flag to the configure script, and it would be invoked as
./configure --with-custom=/some/path/to/extra/source/files
A variable called CUSTOMROOT is added to the make.inc file. The main Makefile will copy all files in the CUSTOMROOT directory to the build directory. This is the last copy, so it will override any of the standard source files from the $RAYLEIGHDIR/src directory.
=> add Custom directory option to configure with the --with-custom=* flag

Jenkinsfile
As discussed at our last zoom meeting this is a file that tells CIG's jenkins testserver (https://singleb.cse.ucdavis.edu/) how to build rayleigh, and what to do for testing. Currently, it just compiles the code and runs the benchmark example case. It does all of that inside a docker container (which is destroyed after the test run), and I had a few problems running Rayleigh with MPI inside the container, which is why it is currently running in serial. I will open separate issues about the MPI issues and the docker containers.
=> Add a Jenkinsfile for the tester setup

configure
The version string of my gcc compiler (7.3.0 the default version that comes with ubuntu 18.04) reports itself as `gcc` not `GCC`, and `gfortran --version` reports `GNU Fortran`, thus the current compiler checks for GNU compilers did not work for me. This should fix the issue. Was there a special reason you check for the name of the command being `gcc`? Because I have my environment variables often set to the MPI wrappers, and `mpicc` should be just as valid as `gcc` if it uses the gcc compiler.
=> Add more checks for GNU compilers

etc/make_dirs
I do not think I was supposed to run this script (I got an unrelated error and was looking for a solution), but I think this script should be run by the default system shell instead of the c-shell. `mkdir` does not require the c-shell, and I for example did not have it installed.
Is this script only supposed to be run on clusters that do not support the creation of directories from the main code? If so, I can add a comment at the beginning to make that clear.
=> Use /bin/sh instead of /bin/csh for making directories

Makefile
This prevents some versions of make getting confused by the fact that an INSTALL file exists already in the repo.  The distclean is just done for completeness.
=> Make install and distclean phony targets in the Makefile.

doc/src/user_guide/Rayleigh_User_Guide.tex
Specifically, use better defaults for the 'listings' and 'hyperref'
styles.
=> Add latex styles for a more functional manual.

configure
`\t` is not recognized by sed on macs as being a tab so rayleigh.opt became rayleigh.op
This is an attempt at fixing that (very) minor bug/feature.
I've tested this on a mac osx 10.13 and ubuntu 18.04.  Might be worth testing elsewhere too.
=> Change the sed whitespace removal in configure to be mac friendly.

src/Diagnostics/Diagnostics_Linear_Forces.F90
The radial component of the viscous stress had a minus sign error in
the term involving the radial derivative of the dynamic viscosity.
The sign in front of the logarithmic derivative of the reference state
density was wrong. A correction was made to both the fluctuating and
mean viscous forces. The viscous force computed from the full velocity
field is computed elsewhere and passed through a buffer. So, no correction
to that term was made.
=> Corrected a minus sign error in Diagnostics_Linear_Forces.F90 

src/Diagnostics/Diagnostics_Linear_Forces.F90
The logic previously asked if the prime-prime component was wanted, but the mean-mean is actually calculated. Now the logic asks if the mean-mean component is wanted.
=> fix Issue #13: a typo in diagnostic logic for buoyancy term.

src/Diagnostics/Diagnostics_TurbKE_Budget.F90
Corrected a mistake in the spherical geometry in the diagnostic computation of the viscous transport of turbulent KE
In the section of the code where the viscous transport of turbulent KE is
computed, there was a mistake in the radial component of the vector Laplacian
of the velocity field. In particular the term involving du_phi/dphi lacked the
necessary preceeding factor of 2 and there was a extra factor of sin(theta) in
the denominator.
=> Corrected a mistake in the spherical geometry in the computation of the viscous transport of turbulent KE

doc/src/user_guide/manual.bib
This adds a .bib file to the documentation with the references cited in the user guide at the beginning of sections. It DOES NOT implement the .bib file. Additional work will need to be done at another hack to implement the autogeneration of the Reference section and use of this file.
=> Add .bib file to user guide.

src/Diagnostics/Diagnostics_TurbKE_Budget.F90
All of the fluxes computed in Diagnostics_TurbKE_Budget.F90 had an
overall sign error. We want the fluxes to obey,
dE/dt = - div.Flux
The sign of the output was changed to obey this relation. The explanatory
comment line for each routine was also modified to be consistent.
=> Fixed the signs of the turbulent KE fluxes

configure
Modified configure to ensure that only a single executable is built with debugging flags. Previous behavior was to build both rayleigh.opt and rayleigh.dbg, but both would have debugging flags. This should work for both Intel and Gnu compilers.
=> ensure configure only builds one executable with the -devel flag

src/Utility/cmkdir.c
The current `#include` directive simply uses the wrong file as shown by `man -S3 mkdir`.
=> Fix the necessary #include path for 'mkdir'.

src/Math_Layer/Legendre_Transforms.F90
Legendre_Transforms.F90 explicitly uses the Timing module, but no routine from the Timing module is ever called. I removed the "use Timing" line and it successfully compiled in devel mode.
=> Remove unused module dependency from Legendre_Transforms

src/Diagnostics/amom_equation_codes.F, src/Diagnostics/induction_equation_codes.F, src/Diagnostics/kinetic_energy_codes.F, src/Diagnostics/magnetic_field_codes.F, src/Diagnostics/velocity_field_codes.F, src/Diagnostics/vorticity_field_codes.F
Some comments with the :tex: directive were missing the closing "$" required by Latex. There was also a vorticity entry that needed another set of curly braces to separate consecutive square operations:
\omega_\phi^\prime^2 was changed to {\omega_\phi^\prime}^2
=> fix some Latex typos in the Diagnostics/*codes.F files

post_processing/rayleigh_diagnostics.py
Issue #91 occurs because self.qv was not initialized before line 736 and throws an error. Another related bug is at line 798; it would have printed "0" everytime (self.qv was initialized to zero), not the intended list of supported quantities (stored in qv).
The indexing bug is because Rayleigh saves the array indices using Fortran 1-based indexing, Python uses 0-based indexing. This is only an issue with the rad_inds, theta_inds, and phi_inds variables that occur in Shell_Slices, Shell_Spectra, SPH_Modes, Point_Probes, and Meridional_Slices.
=> fix Issue #91 and an indexing bug in rayleigh_diagnostics.py

src/Diagnostics/Diagnostics_Base.F90, src/Diagnostics/Diagnostics_TurbKE_Budget.F90, src/Diagnostics/turbKE_codes.F
Modified the Turbulent KE budget outputs to make them a standard set of outputs: they should now appear in the PDF file of outputs.
1. Moved the code number definitions from Diagnostics_Base.F90 to turbKE_codes.F and added the tex description for each.
2. Added a few trivial outputs that were missing (shear production and azimuthal components of the flux)---involving changes to both turbKE_codes.F and Diagnostics_TurbKE_Budget.F90.
3. Removed some obsolete comment statements.
4. This should make Nick's pull request #95 unnecessary.
=> Make turbKE a standard set of outputs

configure, src/gen_header.sh
Some AVX-512 systems require the MIC-512 flag, while some require the AVX-512, Rayleigh only used the AVX-512 flag before. Compiling with the AVX-512 flag and running on the MIC chips results in an error and Rayleigh never runs. This pull request compiles a 512-enabled binary that is optimized to run on both systems.
I have tested this extensively on the TACC Stampede computer that has both MIC-512 and AVX-512 chips; I used the exact same binary to get scaling results on both chip sets.
=> allow more AVX512 support

src/Physics/Controls.F90, src/Physics/Input.F90, src/Physics/Sphere_Driver.F90
This commit allows Ra, Pm, Pr, and E to be specified at the command line.  Calling syntax works as with other command line parameters.   Parameters are specified by their abbreviation, namely:
./rayleigh -Pr N -Pm M -Ra X -E Y
Note that due to my branching/merging practices, this pull request contains changes associated with my earlier run-timing commit.  That commit should be accepted first.
=> Command-line Nondimensional Parameters

dev_build, src/IO/Spherical_IO.F90, src/Physics/Input.F90
This commit involves one bug fix and one small addition:
Bug fix:  There was a bug that was mentioned during the September hackathon.  Output files which were partially complete prior to restart were subsequently corrupted due to issues with the record numbering.   This commit fixes this bug.
Addition:  Normally I would make this a separate pull request, but I added this functionality while debugging the record-number issue.   Rayleigh now accepts the command-line flags -init and -mag_init which can be followed with the desired value of init_type and magnetic_init_type respectively (overriding the value set in main_input).  This can be useful for scripting in addition to debugging.  Calling syntax:  ./rayleigh -init_type -1  (to restart from a checkpoint, for example)
=> Bug Fix:  Record numbering following restart

post_processing/rayleigh_diagnostics.py, src/Physics/TransportCoefficients.F90
This change puts a routine Write_Transport() in TransportCoefficients.F90, which will write the radial profiles of the transport coefficients to the file "transport" in the simulation directory (similar to the file "reference" written by ReferenceState.F90). Write_Transport() is called by Intialize_Transport_Coefficients(). 
rayleigh_diagnostics.py has also been modified to contain a new class TransportCoeffs that will read the file "transport," similar to the ReferenceState class. The TransportCoeffs object has attributes:
n_r
nu
dlnu
kappa
dlnkappa
eta (if magnetism = .true.)
dlneta (if magnetism = .true.)
=> Added routine Write_Transport() in TransportCoefficients.F90 

src/IO/Spherical_IO.F90, src/Physics/Input.F90, src/Physics/Main.F90
This is a minor bug fix.  I noticed last week that the jobinfo.txt file is created before benchmark-mode overrides are enforced.  When benchmark mode was on, the jobinfo.txt would display incorrect values for Rayleigh_Number etc.   I pulled the write_run_parameters() routine into Main.F90 to fix this.   I also made a few small style edits and removed a commented line in Spherical_IO.F90.
=> Benchmark Mode / Jobinfo.txt Bug Fix

post_processing/rayleigh_diagnostics.py
I just noticed that the recent update to include the heating function in the 'reference' file created by Rayleigh (and corresponding change to the ReferenceState class in rayleigh_diagnostics.py) made it so that ReferenceState is unable to read older 'reference' files--it wants to read nr x 11 floats and this will fail in older files where there is only nr x 10. I modified the ReferenceState class to deal with this issue via "try" and "except" since if it can't read nr x 11 floats, there must be nr x 10. 
In the future, this won't be necessary since all new simulations will include the heating function in "reference." But for now it would be good to have backwards compatibility.
=> Modified ReferenceState to read older files that do not have heating function

post_processing/rayleigh_diagnostics.py
This pull request adds a revised Spherical_3D class to rayleigh_diagnostics.py.    As written,the class was structured very differently from other output-related classes.   In addition, it did not appear to return a dictionary of 3-D arrays as indicated by the docstring.   I have retained that original version, for now, having renamed it to Spherical_3D_multi in case this was something in-development that someone was hoping to come back to.
=> Spherical_3D Class Revision 

src/IO/Spherical_IO.F90
There was a bug in the OpenFile routine that was causing errors occurring when opening a file to be ignored, potentially leading to crashes.   I fixed this bug for OpenFile, and modified the routine so that partial output files are now supported.  This fix applied only to the Serio I/O routine OpenFile, which is used for G_Avgs and Shell_Avgs output. 
I suspect a similar issue exists for OpenFile_Par, which is used for the other outputs.  I will fix the bug + partial file I/O for that routine in the next week or so.
-Nick
=> Bug Fix:  Partial Files & Serial I/O

src/IO/Spherical_IO.F90
This commit provides a revised version of OpenFile_Par that works correctly with partial output files.   Diagnostic outputs that use openfile_par have been adjusted to make use of obj%file_open and obj%create_header.  They have been verified to function properly with partial records upon restart.
-Nick
=> Important Bug Fix:  Parallel Diagnostics Output

Makefile
After running "make" and "make install" the rayleigh.* executables are copied to the $PREFIX/bin/ directory, but when running "make distclean" the makefile was removing executables in the $PREFIX/ directory. This does not delete the intended files and could potentially delete files that were meant to be saved. Now the makefile deletes only what it is supposed to.
=> Makefile now removes installed exectuables using proper directory

Jenkinsfile
This tells Jenkins to clean up files created by the build.
=> Add cleanWs to post build step

src/Diagnostics/Diagnostics_Angular_Momentum.F90, src/Diagnostics/amom_equation_codes.F, src/Physics/Sphere_Linear_Terms.F90
This commit provides 2 important bug fixes:
1)  When advect_reference_state was set to True, the array necessary for holding the assocated W coefficients for the Tvar equation was not allocated.   Models previously run with this flag would crash (usually).  Sometimes, they would generate junk results due to memory being written OOB.
2) The strict_L_conservation flag has been fixed.   Over long-time integrations, particularly in models with magnetism and or stable regions, errors arising from the accuracy of the time-stepping scheme can accumulate, even when run with stress-free boundaries.  An integral constraint on the ell=1 toroidal streamfunction can fix this.    Effectiveness of the fix is demonstrated in the image below.  The blue line sits at 1e-2  and the green line sits at 1e11. …
=> Critical Bug Fixes:  Ref-advection and L-conservation

src/Diagnostics/turbKE_codes.F
This adjustment references the turbulent kinetic energy codes to the magnetic energy codes.  Between these two code sets is the custom diagnostic block.  This was causing issues in the auto generation of quantity code tables (anything after the custom code block would fail to compile).
=> turbke_offset is now referenced properly to meq_offset.

post_processing/convert_full3d_to_vtu.py
Spherical_3D has been renamed Spherical_3D_multi (because another class has taken the name Spherical_3D).
Some python3 fixes (no iteriterms, xrange).
Copyright notice had broken the #!.
=> A few fixes for convert_full3d_to_vtu.py

Jenkinsfile, docker/rayleigh-buildenv-bionic/Dockerfile
It looks like the problems we had with using OpenMPI inside the docker container that we use for testing do not occur with MPICH (at least locally when I run the container on my laptop). I would like to see if that is also the case on the jenkins server. If this works then we can start running some more test models for every pull request.
Please do not merge this until I have verified that it is ready.
=> Fix parallel test error

doc/source/conf.py
This sets up the cover page of the pdf version of the sphinx documentation to look exactly like the current CIG manual template:
=> Make cover page of sphinx documentation

Jenkinsfile, doc/source/conf.py, docker/rayleigh-buildenv-bionic/Dockerfile
This is a first simple way to test that no PR breaks the Sphinx build. While readthedocs would show us a broken build after its broken, this should prevent us from merging documentation that does not compile. It does not prevent documentation that formats incorrectly, and it also does not automatically update the documentation.
=> Add an automatic test for the documentation

doc/source/conf.py
This removes a warning during building the sphinx documentation. We currently have no static files for the html documentation and no directory `_static`.
=> Fix a sphinx warning

doc/source/conf.py
This fixes a warning about python2 code for sphinx. Not sure why, but tested to work on 2 different systems.
=> Prevent a warning about python2 code

Makefile, etc/check_ipynb_cleared
This adds a script to check that output is cleared from Jupyter notebooks. There is also a make target to clear the output in all notebooks.
Ideally, we would include the check in the test suite, possible with a whitelist of notebooks that we store with output.
=> Clear output from Jupyter notebooks

README.md
This adds links to the online documentation to the README, so that they are easily reachable from the github start page.
=> Add online documentation to README.md

doc/source/User_Guide/index.rst, doc/source/User_Guide/overview.rst, doc/source/User_Guide/publications.bib, doc/source/User_Guide/publications.rst, doc/source/User_Guide/publications2016.bib, doc/source/User_Guide/publications2018.bib, doc/source/User_Guide/publications2019.bib, doc/source/User_Guide/software.bib, doc/source/conf.py, docker/rayleigh-buildenv-bionic/Dockerfile
Adds a  list of publications to the end of the documentation and fixes a few minor bugs. 
This appears to be a relatively new feature so some work arounds were implemented to have it render in a usable manner. Please note the following. New publications should be added to 2 files:
1.  publicationsYYYY.bib (or software.bib). Add publications to the appropriate .bib file. Publications will print in the order they appear in this file.
2. publications.rst. Add appropriate key under the correct year. 
Needs the the following extension installed:
sphinxcontrib-bibtex
See documentation here: https://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/UsingBibTeXCitationsInSphinx.html
=> Add a Publications List to the documentation

doc/source/vids.rst
This adds an alternative link to the animations in the .pdf documentation. Not as fancy as the html version, but at least is shows a clickable link.
=> Add animations to pdf documentation

doc/source/User_Guide/benchmarking.rst, doc/source/User_Guide/checkpointing.rst, doc/source/User_Guide/physics.rst
This fixes the one table that used a different method to generate. 
It also reformats all table headings so now the titles are now centered.
=> Restore a table and make the rest prettier

.readthedocs.yaml, doc/requirements.txt
Our documentation now requires a certain sphinx extension that is not activated by default on readthedocs. This PR adds configuration files that ensure the correct extensions are installed by readthedocs before building the documentation.
=> Add readthedocs configuration file

Jenkinsfile, Makefile, docker/rayleigh-buildenv-bionic/Dockerfile, post_processing/Diagnostic_Plotting.ipynb
This PR activates an additional check on the tester to automatically fail if one of the python notebooks in the repository contains output cells with output. This output can be large, is reproducible, and should therefore not be included in the repository.
=> Automatically check python notebooks for output

doc/source/User_Guide/index.rst
This fixes a small but prominent error in the user manual.
=> fix typo in title

doc/source/User_Guide/benchmarking.rst, doc/source/User_Guide/index.rst, doc/source/User_Guide/overview.rst, doc/source/User_Guide/physics.rst
Adds and uses a reference section to the manual.  This addresses  #17 .
This keeps _authorname, YYYY_ style referencing inline for readability.
References are in a file separate from publications.
=> Add and use a reference section

src/Physics/Benchmarking.F90
Custom reference states were being overwritten by benchmark mode.  This prevented the benchmark machinery from carrying out verification of custom reference states.  This PR fixes this bug.
=> fixed bug with custom_reference_file and benchmark_mode

dev_build
Super simple change to allow the `dev_build` script to accept variable numbers of arguments to be passed to configure.  This is a wish list item of @feathern that I'm just disentangling from another branch I'm debugging.
=> Allow variadic arguments to dev_build.

configure
As LAPACK depends on BLAS this should be the right order. Fixes the
build with static LAPACK for me on at least one system.
=> link BLAS last

configure, src/Parallel_Framework/Ra_MPI_Base.F90
Falling back to the F77 MPI bindings can help to compile the code on
systems where the current compiler does not match the one used to
compile MPI. This is not the default, of course.
=> add configure option to use mpif.h

configure, dev_build
This adds a few options to help track down the origin of NaNs. Is there any occasion where Rayleigh produces NaNs in regular operation? In that case we might want to switch off the floating-point exception traps.
=> improve debug builds

docker/rayleigh-buildenv-bionic/Dockerfile, tests/generic_input/run_test.sh, tests/generic_input/test_output.py
This piggybacks on the generic_input test by converting the full 3d output to vtk and then testing the contents of the resulting files match.
=> Add a tester for convert_full3d_to_vtk.py.

configure
This enables conda-installed MKL support by setting MKL lib paths to MKLROOT/lib instead of MKLROOT/lib/intel64. The FFTW include path is changed from MKLROOT/include/fftw to MKLROOT/include.
If using conda-supplied MKL, run with ./configure -mkl -conda-mkl or ./configure --with-mkl='/my/mkl/path' -conda-mkl.
If this flag isn't set, conda-installed MKL libraries will not be referenced properly by the compiler flags set via ./configure.
=> Added -conda-mkl flag to configure script.

src/Makefile.fdeps
One of the PRs this week changed the dependencies without updating the depency file (maybe it is also just the build type of the tester?). This should fix the results. Only merge if the tester succeeds.
=> Fix dependency file for tester

configure
This commit adds support for linking the MKL library on Macs.  Presently, only conda-installed MKL is supported.     This is configuration is enabled by passing the -mac-mkl flag to configure.  In addition, I changed things around so that the -conda-mkl flag can be used without the -mkl flag.  Initially, they had to be used to together, but that felt redundant.
The reason for these conda flags is that I am planning to add some documentation on setting up a conda environment for building Rayleigh and the docs.
-Nick
=> Added -mac-mkl flag to configure

doc/source/User_Guide/devel_environment.rst, doc/source/User_Guide/index.rst
This PR adds documentation describing how to set up a single Conda development environment that allows you to compile both Rayleigh and its documentation.
In order for these instructions to work completely, PR 206 needs to be approved.
In the meantime, if someone could test this, that would be great.  Just add an extra -mkl flag to the flags already specified for configure.  I will check for typos tomorrow or correct them soon if this is merged quickly.
-Nick
=> First draft of conda instructions.

src/Physics/Sphere_Spectral_Space.F90
This PR fixes a bug where reference-state advection was improperly implemented.   The term v dot grad dsdr is linear and implemented semi-implicitly through the CN scheme.   As it stood, only the implicit portion (left-hand side) was implemented.  The explicit portion (right-hand side) had been omitted.   The RHS is now properly addressed through this PR.
=> Fixed reference-state advection bug.

post_processing/reference_tools.py
This allows us to directly reference functions and coefficients by name
from the equation_coefficients class.
Example:
```python
cref = rt.equation_coefficients(file='equation_coefficients')
cref.density
```
=> direct attribute access in equation_coefficients

src/Physics/PDE_Coefficients.F90
Previously the entropy gradient dsdr was set to zero in the Polytropic_Reference() routine of PDE_Coefficients.F90. It should only be zero if poly_n = 1.5 (albeit the most common--i.e., solar--case). I replaced it with the correct dsdr from the First Law of Thermodynamics. This distinction is important, since before Rayleigh was effectively unable to run the stable polytrope case. 
I am attaching a figure showing the difference; this case has poly_n = 4.5 and advect_reference_state = .true., one with the old version of the code (dsdr0) and one with the new fix. For the old code, there is still still convection, when clearly there shouldn't be as the case is (very) stable to convection. For the fixed code, there is a purely conductive state, as there should be. 
The same dsdr = 0 happens …
=> Fixed dim polytrope

src/Physics/PDE_Coefficients.F90
This is the second in a series of commits to properly set the equation coefficients in the "equation_coefficients" binary file. The first dealt with the diffusion coefficients, (c_5, f_3), (c_6, f_5), and (c_7, f_7) and was approved. This deals with the other c's/f's in the non-dimensional boussinesq case (reference_type = 1 and the Constant_Reference() subroutine).
=> Set equation coefs reftype1

examples/custom_reference_states/MESA-input-1Msun-ZAMS.ipynb, examples/custom_reference_states/main_input_mesa
`p_fact` wasn't set in the MESA example, which caused the setup to produce NaNs on the first time step. This fixes it and adds an example `main_input` file as well.
=> fix MESA example

src/Physics/BoundaryConditions.F90, src/Physics/PDE_Coefficients.F90
This is the fix I mentioned to set c_10 and f_6. I believe it should work in all cases. f_6 should always volume-integrate to 1, leaving c_10 to be the heating_integral or luminosity set in main_input. 
This pull request has three commits to make it modular in case I screwed something up. 
1. The first commit gets rid of the setting of c_10 and f_6 in the subroutine Constant_Reference(), as @orvedahl, @feathern, and I discussed. 
2. The second commit sets c_10 and f_6 in Initialize_Reference_Heating()--this should work for all cases, but please comment if I am mistaken. 
3. The third commit gets rid of what appears to be a no longer used flag: adjust_reference_heating. I think this flag used to normalize the heating based on the desired luminosity AND whatever energy is lost (or possibly …
=> Set heating coefs

doc/source/User_Guide/running.rst, src/Physics/Controls.F90, src/Physics/Main.F90, src/Physics/Sphere_Driver.F90
This makes it possible to cause Rayleigh to exit and write a checkpoint
file by touching a file called "terminate" in the run directory. This is
convenient for restarting with new options without losing any progress.
With the right logic in the job script, even the current allocation in
the queue can be kept.
As checks for the existence of a file can be costly on some parallel
file systems, the default is to check only every 50 iterations. This can
be configured with `terminate_check_interval`.
The section "Running the code" in the documentation has been updated to
describe this feature.
=> add option to cause orderly shutdown by touching a file

src/Physics/PDE_Coefficients.F90
This should properly set the equation coefficients for reference_type = 2 (Polytropic, dimensional). This leaves only the routine Polytropic_ReferenceND() to modify, which @feathern says he'll do (although, Nick I did do this routine as well if you'd like to see my branch before I or you make another pull request). 
Right now, the Finalize_Equation_Coefficients() routine only modifies ra_constants() and ra_functions() for reference_type = 3. After reference_type = 3 sets the functions/constants itself, we should probably eliminate Finalize_Equation_Coefficients() and have simply a call to Write_Equation_Coefficients() in Main.F90. 
Please review to make sure I set the coefficients right!
=> Set equation coefs reftype2

doc/source/User_Guide/io_redirection.rst, doc/source/User_Guide/running.rst, src/Physics/Controls.F90, src/Physics/Sphere_Driver.F90, src/Utility/BufferedOutput.F90
This allows us to monitor the code performance during a run. It also
includes iter/(sec*ncpu), which is a basic indicator of scaling
efficiency when changing the number of processes.
The new status line looks like this:
```
On iteration : 00000004    DeltaT :   1.0000E+03            0.23 iter/sec,       0.12 iter/(sec*ncpu)
```
I normally use sec/iter instead of iter/sec, but I picked the later to be consistent with the timing output when the code terminates.
This uses an existing timer (`walltime`), so it should not incur any significant overhead.
As this is quite a prominent change in the log output, I think we should collect a few opinions before merging.
=> output iter/sec on every iteration

src/Physics/Main.F90, src/Physics/PDE_Coefficients.F90
After this pull request, all default reference_types should properly initialize the equation_coefficients. @feathern (or someone else!) please verify the constants/functions in PolytropicReferenceND(). 
The 1st commit adds the setting ra_function/ra_constants in PolytropicReferenceND().
the 2nd commit modifies Finalize_Equation_Coefficients() to only write the equation_coefficients file (and not "finalize" anything), since theoretically all the functions/constants will have been set by this point. 
The 3rd commit removes the finalize_equation_coefficients() routine entirely, since now this routine is theoretically unnecessary. Main.F90 then calls Write_Equation_Coefficients_File() directly. This is a bit more of a substantial change (modifying "Main") and so is a separate commit that can …
=> Set equation coefs reftype3

configure
This uses a dialog similar to the one for the Intel compiler. I also
added an option to use automatic detection of the right instruction set,
provided the compiling node is the same as the compute node. The result
of auto-detect is displayed.
The option for producing several executables should work as well.
I chose the same selection as in the Intel compiler.
=> enable machine-dependent SIMD optimizations also for GNU compilers

doc/source/User_Guide/devel_environment.rst
This fixes a very small typo in the MKLROOT instructions of the development environment section.  I noticed it when following along on a new OS just now.  I'm going to approve/merge this since the change is tiny and it's related to an old commit of my own.
=> Fixed typo

src/Physics/Generic_Input.F90
MPI_TYPE_EXTENT has been deprecated for a while apparently so this pr gets rid of it.
I've tested this for backwards compatibility to 2.1.1 and compiled it against 4.0.1.
=> Replace MPI_TYPE_EXTENT with MPI_TYPE_GET_EXTENT

configure
`libopenblas` already comes with a full set of LAPACK routines included. While you can link another LAPACK library at the same time, this might override the (possibly) more optimized functions from OPENBLAS. Also this way Rayleigh doesn't compile on systems that only provide `libopenblas` but not `liblapack`.
This patch avoids linking against `liblapack` if the `--openblas` option is set.
OPENBLAS can be compiled in a non-default mode that does not include LAPACK. I have never seen this on any production system. If this is a concern, we could add an additional option or maybe even an automatic detection.
=> do not link against LAPACK if using OPENBLAS

src/Physics/BoundaryConditions.F90, src/Physics/Initial_Conditions.F90, tests/generic_input/run_test.sh
This pull requests fixes one bug and adds one feature:
1.) The value of br_bottom set when  impose_dipole_field = .true. was not reflected in the dipole initialization routine.  Moreover, the coefficient for C(ell=1, m=1) was wrong by a factor of sqrt(2), causing a tilted dipole to have a lower amplitude than one purely aligned with the z-axes.  These inconsistencies have been fixed.
2.)  A dipole naturally satisfies the potential field boundary condition at the upper boundary.  This means there is no inconsistency between using potential match at the top and imposed dipole field at the lower boundary.   This can now be done by setting dipole_field_bottom = .true. in boundary conditions namelist.
=> Dipole Field Boundary Conditions

src/Parallel_Framework/Parallel_Framework.F90, src/Physics/ProblemSize.F90
This PR fixes a segmentation fault caused by Rayleigh not exiting properly in some instances after the parallel framework is finalized.  I noticed this when trying to run with npcol > nr (not allowed).  In that case, MPI is finalized, but the code continues to try to run and ultimately attempts to reference an unallocated array.  A proper call to Fortran's intrinsic Exit function now follows the MPI finalization in Parallel_Framework.F90.  
In addition, a non-zero error code is now passed to the shell when an error is encountered in the grid/process-configuration consistency check at initialization.  The error code reported now isn't particularly meaningful, but it's non-zero as it should be.
To see the issue and the resolution, try both the master branch and this PR version via:
mpiexec …
=> fixed exit status / seg-fault issue

src/Diagnostics/Diagnostics_Induction.F90
I think there is a sign error in how the magnetic diffusion term and the "diffusion work" terms are calculated. The induction equation has a term on the RHS that looks like "- del x [eta del x B]" and the work term is the inner product of that term with B. Using a few vector identities this term can be written as
- del x [eta del x B] = eta del^2 B + J x grad(eta) = eta del^2 B + [0, Jphi*dr(eta), -Jtheta*dr(eta)]
The sign error is in front of the "J x grad(eta)" term. Someone should definitely check my math though.
=> Sign error in magnetic diffusion diagnostics

configure
After wondering why Rayleigh didn't compile for a while, I figured that it should really throw an error if you pass unknown options to `configure` instead of silently ignoring options with a typo.
=> throw an error message if unknown options are passed to configure

src/Parallel_Framework/Parallel_Framework.F90, src/Physics/ProblemSize.F90
Firstly, please don't merge this yet!  I'm looking for feedback + a little beta testing if anyone has the time.  
This PR adds new functionality to Rayleigh.  Sometimes I get tired of specifying nprow and npcol every time I run the code.  I also suspect it's a little annoying to think about the process grid when you're just trying to run the code for the first time.   With this PR,  if nprow and npcol are not specified in main_input or at the command line, Rayleigh will identify the nprow/npcol pairs whose product equals ncpu.  It will then identify all pairs that are consistent with the chosen problem size and finally attempt to pick a sensibly optimal pair.
This way, you can just say "mpiexec -np 8 ./rayleigh.opt" and it will hopefully run.
Here's a summary of how the optimal pair is …
=> Automatic Domain Decomposition

src/Makefile.fdeps, src/Math_Layer/Ra_Precision.F90, src/object_list
This PR adds a precision module to Rayleigh.   The current syntax used by Rayleigh when declaring variables is Real*8 instead of Real(Kind=X).  The former is outdated and not considered portable.   I would like to move toward a more portable format where all variables are declared with kind=x, and where x is taken from the ISO_Fortran_Env intrinsic module.
This PR is intended to lay groundwork for updating the variable declarations.  It only adds a precision module to Rayleigh that provides double-precision (ra_dp) and 4-byte-integer (ra_int) kinds.  The module Ra_Precision sits at the base of the dependency tree and is currently only "used" by Math_Constants, and only through a use statement.  Math_Constants doesn't actually use ra_dp or ra_int.   This was done so that "make fdeps" …
=> Precision Module

src/Physics/Checkpointing.F90
I accidentally transposed two array indices in checkpointing when I implemented the new parallel IO interface.  The result was that the code would crash on restarts if the radial resolution was also increased.  This PR fixes that bug.  It's a one-line fix, so I'm going to just merge it now.
=> Bug Fix: Restarts with Higher Radial Resolution

post_processing/rayleigh_diagnostics.py, src/IO/Parallel_IO.F90, src/IO/Spherical_IO.F90
This PR addresses a potential performance issue resulting from the revised parallel I/O.  The small write sizes associated with Shell_Avgs and G_Avgs outputs can lead to significantly diminished I/O performance on Lustre file systems (as seen on Pleiades; possibly other file systems as well).   These two outputs are now striped differently, with each process writing all of its data at once, as opposed to one quantity-code at a time.  The drawback is that the data ordering for Shell_Avgs now depends on the process configuration (specifically the value of npcol).  New metadata has been added to Shell_Avgs and rayleigh_diagnostics.py has been updated to facilitate reading this new striping pattern.
Version numbers of both outputs have been updated from 5 to 6.
I note that Point_Probes are …
=> Important I/O Performance Adjustment

src/IO/Parallel_IO.F90, src/Makefile.fdeps, src/Physics/BoundaryConditions.F90, src/Physics/Checkpointing.F90, src/Physics/Controls.F90, src/Physics/Input.F90, src/Physics/Main.F90, src/Physics/PDE_Coefficients.F90, src/Physics/Run_Parameters.F90, src/Physics/Sphere_Driver.F90, src/object_list
This PR changes the checkpoint format used by Rayleigh.  It's one of the last major changes I would like to push through before a 1.0 version release (we're at 0.95 now).   These modifications are fully compatible with old checkpoint files -- nothing new needs to be done to restart from the old format.    Rayleigh checks for the new format first when reading a checkpoint.  If that's not found, it drops back to the old format.
When new checkpoints are written their format differs as follows.
1.) Each checkpoint now gets a dedicated directory into which all checkpoint files are stored.  This directory contains all information needed to restart a model.
2.) In addition to the old files (e.g., W, PAB, etc.) a main_input file, an equation coefficients file, and a boundary conditions file are …
=> Portable & Complete Checkpoints

post_processing/YT_volrender_tutorial1.ipynb
The Compile_GlobalAverages routine used the old GlobalAvgs object name, instead of G_Avgs.  The routine was broken as a result.  This is a quick, name-change edit, and so I will merge without review.
=> Fixed issue in Compile_GlobalAverages.

post_processing/rayleigh_diagnostics.py
The TimeAvg_ShellAverages routine in rayleigh_diagnostics.py now works properly with all version (1, 2 through 5, and 6+) of the Shell_Avgs outputs.   The old class name ShellAverage has been changed to the current name Shell_Avgs as well.  This routine was completely broken before this pull request.
=> TimeAvg_ShellAverages now works with all Shell_Avgs versions

src/Physics/PDE_Coefficients.F90
This fixes a bug where nu_top, kappa_top, and eta_top were not properly being set when  reference_type =4 and the related constant was set in the custom input file.  This PR adds the following, originally intended logic for nu{kappa,eta}_type = 1 or 2.   
1.  nu_top, kappa_top, and eta_top all default to -1 now unless explicitly set in main_input.
2. If any of these are left at their default value, the values from the custom reference file are used.
3. If any of these possess a non-negative value due to being set in main_input, that value will override the associated rayleigh constant set in the custom-reference file.
Similar logic now applies to angular_velocity.  It defaults to -1, but if set, it will be used to set the Coriolis term (2 x angular_velocity), and the related rayleigh …
=> Custom Reference Fix #1

src/Physics/Input.F90
Each line in the namelist was assumed to be less than 512 characters. This means if you have more than about 120 quantity codes, then Rayleigh will truncate the line and it will not add the requested codes (and not tell you that it happened). I increased the limit from 512 to 2048, which would allow something on the order of 400 quantity codes.
In theory, Rayleigh will accept 4000 quantity codes, which would require the line length to be something like 18000, but you would probably hit a memory error well before that limit.
=> Allow more quantity codes in the Namelist

src/Physics/Main.F90
This small change to Main.F90 calls Initialize_Transport_Coefficients before (instead of after) Initialize_Boundary_Conditions.   Otherwise, the subroutine 'Transport_Dependencies' will cause a crash if adjust_reference_heating is true and fix_dtdr_top or fix_dtdr_bottom are also true.  In practice, this only affects reference_type = 3 (the Jupiter model).  This bug was introduced when we combined reference-state and diffusion-related quantities together into the PDE_Coefficients module.   Since this is critical to one user's workflow, I am merging without review.
=> Bug Fix:  Adjust Reference Heating

Makefile
Before, the interp3d executables were moved to bin/ which may or may not have previously existed and is not necessarily the same location that the Rayleigh executables were installed.
I added the PREFIX location to the copy command: "cp $(INTERP)/interp3d $(PREFIX)/bin/."
=> Install the interp3d executable to the same location as Rayleigh

src/Physics/PDE_Coefficients.F90
These were always thrown when reference_type = 4 regardless of the diffusion_types. I also standardized the formatting of the error messages. This branch is based off the luminosity_flag branch.
=> Removed duplicate error messages for transport coefficients functions/constants

src/Physics/Checkpointing.F90
I thought I had already merged this into the main branch...
This fixes an integer-arithmetic-related bug where checkpoint files larger than 2 GB were erroneously found to have the wrong filesize at init time.  All variables used in the size-check calculation are now 8-byte Integers.
=> Checkpoint Size Bug Fix

src/Diagnostics/Diagnostics_Angular_Momentum.F90, src/Diagnostics/Diagnostics_Linear_Forces.F90, src/Diagnostics/Diagnostics_Lorentz_Forces.F90, src/Diagnostics/Diagnostics_Mean_Correction.F90
Four of four. "angular_velocity" is only used for dimensional runs; 1811 and 1812 should have used ref%Coriolis_Coeff/2.0. Currently they will be computed incorrectly using angular_velocity = -1 (its default value) if user does not specify angular_velocity, as in a nondimensional run or custom run.
=> Fix misuse of angular velocity in diagnostics

src/Diagnostics/Diagnostics_Linear_Forces.F90, src/Diagnostics/Diagnostics_Mean_Correction.F90
First in a series of four (4) small bug fixes to the diagnostics. In this one, there was a sign error in the "estress" term appearing in radial viscous force and derivative quantities.
=> Fix sign error v r times vforce r

src/Diagnostics/Diagnostics_Linear_Forces.F90, src/Diagnostics/Diagnostics_Mean_Correction.F90
Two out of four. Missing call to AdotGradB that prevented vm_dot_grad_vm_r from being computed properly in Diagnostics_Mean_Correction.
=> Fix vm grad vm terms

src/Diagnostics/Diagnostics_Linear_Forces.F90, src/Diagnostics/Diagnostics_Lorentz_Forces.F90, src/Diagnostics/Diagnostics_Mean_Correction.F90
Three out of four. Typo in Diagnostics_Lorentz_Forces, line 176, meant that mag_work_mpp (1919) would never be added.
=> Fix mag work mpp

src/IO/Parallel_IO.F90, src/IO/Spherical_IO.F90
This update allows Rayleigh to deal gracefully with an easy source of user error.   When the new I/O interface was written, the indexing logic for output data was changed slightly.  If duplicate and/or non-existent quantity codes were specified via main_input, an indexing variable was improperly incremented, leading to corrupted output.   This is a pretty easily-expected source of user error, and so Rayleigh should guard against this.  This update fixes the logical issue, and the output is no longer corrupted.  The new behavior is as follows:
1) If a valid quantity code is specified multiple times, it only appears once in the output file.  The file appears exactly as though no duplicates were specified in main_input.
2) If an invalid quantity code is specified, it does not appear in the …
=> Critical Bug Fix: Duplicate/Non-existent quantity codes no longer garble output

post_processing/rayleigh_diagnostics.py, src/IO/Parallel_IO.F90, src/IO/Spherical_IO.F90
This partially fixes a bug related to the power spectra normalization.  Generally, shell_spectra power should satisfy Parsevals's theorem, such that the integrated power (e.g., v* v) over ell and m is equal to the integral of v^2 over the shell in physical space.  For some reason, the m!=0 power is too high again by a factor of 2.  This was fixed in shell_spectra version 4, but seems to have crept back in in version 5.  
I will look into the Rayleigh source later to see where/why this happened again, but for the time being, this quick fix in rayleigh_diagnostics.py will correct the problem for all versions except for version 4.
=> Shell Spectra Once Again Satisfy Parseval's Theorem

doc/source/User_Guide/devel_environment.rst
This changes the installed packages to ensure `mpif90` and `mpicc` are available.
It also changes the way `MKLROOT` is set. `CONDA_PREFIX` is a more reliable way to find where the current conda environment is installed, particularly on macOS.
I also took the liberty to quote all the used shell variables in case someone is daring enough to have a space in their conda path.
=> update Conda environment documentation

conf.py
Just add a list of the bibfiles to `conf.py`
This appears to work with sphinxcontrib-bibtex==2.2.1 but is untested on other versions.
=> Add the bibtex files to conf.py for make doc

configure
To correct the following error when compiling using a Mac:
ld: library not found for -lstdc++
=> Updated configure file for mac: lstdc++ to lc++

doc/source/User_Guide/devel_environment.rst
These are some instructions for using the Docker container as a development environment. It uses our current Docker container on Docker Hub at the moment. In the future we might want to switch this to a newer build environment.
I chose to mount the home directory at `/root`. This has the advantage that `cd` goes to the right home directory and we can use the SSH keys from the normal home directory for git. I don't see a big problem in running the code as root inside the container, but if others prefer we could create an unprivileged  user inside the container. The downside would be that the users can't use `apt` directly to get new software.
=> add instructions for building and using the Docker environment

src/Makefile
The `echo` prevents `make` from returning a nonzero exit code on failure.
Removing it makes it exit on error.
Fixes #15.
@feathern was there a specific reason to include the `echo`?
=> remove echo after call to make

.github/workflows/linux.yml, tests/generic_input/run_test.sh
I added an environment variable to add OpenMPI specific options into the generic_input test run script. This should avoid conflicts with running the script under different  MPI implementations.
With these changes the new github test action now runs all of the tests that the old Jenkinsfile has. In principle the Jenkins tester is now not longer needed (but we can run it in parallel for a while, before removing the Jenkinsfile).
=> Improve test action

Makefile
The default behavior when typing "make" is to build the debug version as well as the optimized version. This PR allows you to specify a particular version of Rayleigh to build by typing "make target=opt" or "make target=dbg". The default behavior is to build everything, just as before.
=> Allow building a particular version of Rayleigh (dbg, opt, etc.)

configure
When running ./configure a compiler-dependent preprocessor flag is included such as "-DINTEL_COMPILER" or "-DGNU_COMPILER". When specifying custom flags such as "./configure --FFLAGS='-O3' ..." the preprocessor flags were overwritten and lost, even when using Intel and GCC compilers. This PR adds all preprocessor flags after the custom flags have been applied, i.e., fix for Issue #144
=> Fix for Issue #144: internally used preprocessor flags are no longer overwritten by custom flags

INSTALL
This updates the formatting of the INSTALL file. Two things changed:
- remove version number and author from the header, version number is irrelevant, because these instructions are for the current version (which may change), and the author is listed in the AUTHORS file.
- reformatted lines that were longer than usual line length conventions, making it easier to read in simple text editor. No text was changed, just moved line breaks to different places.
=> Update INSTALL formatting

environment_mac.yml
Mac, conda environment: the code would compile, but got the following error when trying to run it:
mpiexec -np 8 ./rayleigh.opt -nprow 4 -npcol 2
Fortran runtime error: Integer overflow when calculating the amount of memory to allocate
This is intended to fix this bug.
=> Conda environment file for mac

src/IO/Spherical_IO.F90, src/Physics/Benchmarking.F90, src/Physics/Input.F90, src/Physics/Run_Parameters.F90
Compiling using intel with '-check all' stops at runtime on uninitialized variables. This pr fixes some found running a Boussinesq hydro benchmark.  There are likely more.
It would be good if someone else could check my initialization of some of these.  In particular `ref_remember`.
=> Fixing some uninitialized variables found by the intel compiler.

environment.yml, environment_mac.yml
Only mac so far, will give linux a quick whirl now.
Removed duplicate dependency on sphinx, added in vtk and funcsigs to allow generic input tests to run.
=> Fix the versions in the conda environment to ones that are currently known to work

.github/workflows/linux.yml
This adds an automatic MacOS tester that builds the Rayleigh conda environment for Mac.
It seems the tester fails, because Mac's default `ld` does not recognize the `--no-as-needed` option. Will investigate further later.
=> Build mac env

ACKNOWLEDGE, doc/source/User_Guide/overview.rst, src/Physics/Main.F90
Currently we explain how to cite and acknowledge Rayleigh in different location. This PR unifies this handling by letting the ACKNOWLEDGE file refer to the web documentation (or the local one for everyone without internet connection).
Also make clear with every Rayleigh run, where to look for citation information. The output now looks like the following:
```
-- Initializing Fields...
---- Specified parameters:
---- Hydro Init Type    : Benchmark (Christensen et al. 2001)
-- Fields initialized.
Initialization Complete.
//////////////////////////////////////
Remember to cite Rayleigh in your publications:
Check the ACKNOWLEDGE file for more information.
//////////////////////////////////////
Timestep has changed from  0.00000E+00 to  1.00000E-04.
Iteration:  00000001   DeltaT:  1.000E-04 …
```
=> Unify acknowledgments and make citation more visible

docker/rayleigh-buildenv-focal/Dockerfile
This breaks the documentation build because the pip version conflicts with the
one from apt. The Ubuntu focal container ends up having an incompatible version
of pygments. The current pip install command pulls in sphinx as a dependency so
there is no need for installing it also via apt.
I am not sure if this fixes the documentation build issues producing all italics because I couldn't reproduce the issue on my system.
=> do not install sphinx via apt

Makefile, doc/source/User_Guide/installation.rst
The default behavior when you do "make target=opt" is to build only the optimized executable and it will be named "rayleigh.opt". Similarly, "make target=dbg" will build the debug version "rayleigh.dbg". The executables are then placed into the bin directory with "make install", but the filenames are always rayleigh.opt or rayleigh.dbg.
When actively developing multiple branches, it can be a little hard to keep track of what executable came from what branch. This PR allows you to change the name of the executable when doing "make install", but only if you requested a particular target.
To build the optimized version and call the executable "branch1.opt", the following would be used:
`make target=opt`
`make target=opt output=branch1.opt install
The resulting executable will be placed into …
=> Allow changing the executable name at the "make install" step

configure
This makes ifort use the `-march` option instead of the equivalent `-x`
option. Executables built with the latter option do not run on non-Intel
CPUs. I am keeping this as a nondefault option as I am not sure if there
is a decrease in performance using `-march`.
There is no direct `-march` equivalent for the AVX512 option. Leaving it
as is, as there is no non-Intel AVX512 processor available at the time
of writing.
=> add new configure option -ifort-march

input_examples/c2001_case1_input, input_examples/j2011_steady_hydro_input, input_examples/j2011_steady_mhd_input, src/Physics/Benchmarking.F90
This flag is no longer used by Rayleigh and will cause the code to crash if not deleted from the "_input" benchmark main_input files.
=> Remove dimensional flag

doc/source/User_Guide/running.rst
This is a simple documentation of the multiple radial domain feature. I don't know any of the internals, this is just from what I figured out by reading the namelist definitions. Review by someone more knowledgeable is appreciated.
I also changed the way the namelist variables are formatted in this section. In my opinion math mode is not a good choice for variable names, in particular because underscores are not formatted correctly. I'm using code formatting (enclosed in ` `` ` marks) instead.
Closes #4.
=> documentation for multiple radial domains

.github/workflows/main.yml
This fixes #277. I saw this in https://github.com/geodynamics/calypso/pull/20 so thanks @hirokemono for showing me the fix.
The results of the CI tests are now clean, as can be seen here: https://github.com/gassmoeller/Rayleigh/runs/3654465525?check_suite_focus=true
=> Remove MPI warnings in CI

post_processing/reference_tools.py
This interface never worked before. With the fix you can do things like `r.diff_fact = 1.0` and it will call the appropriate setter for constants. It already worked for functions.git push --set-upstream origin fix-set-constant
=> fix attribute access in reference_tools

.readthedocs.yaml, doc/requirements.txt, environment.yml, environment_doc.yml
Our development environment and the environment that builds the documentation should ideally be the same environment to make sure things look and work the same online and locally. But the development environment also needs a lot of stuff that the doc environment does not need (we dont need mkl on readthedocs to build the documentation). This change includes the doc/requirements.txt file into the environment.yml to make sure they always use the same packages.
The documenation should be unchanged. Let's see what the conda tester says.
=> Reduce duplication in doc and devel environments

configure
The options are very similar to gfortran. Some some checks (array
boundaries, FPE etc.) are not supported and have been removed for now.
Signal handling is also not supported at the moment.
This has been tested with AOCC version 3.0.0
=> add support for LLVM-based AOCC compiler by AMD

src/Physics/PDE_Coefficients.F90
The equation_coefficients file was going to the parent directory in ensamble mode, due to a missing "my_path" in front of the file name.
=> Small bug (missing pathname) for equation_coefficients file

post_processing/rayleigh_diagnostics.py
I just realized that the rad_inds and theta_inds attributes of the Point_Probes class were not documented in the doc_string.   The phi_inds attribute was documented, but mislabeld as phi indices.  This  PR fixes these three errors.
=> Point_Probes docstring update

src/Physics/PDE_Coefficients.F90
Read_custom_reference_file was originally written as though the input parameter 'filename' was optional.   In practice, that filename is always supplied, making a few lines of code in this routine obsolete.  This PR removes those lines of code.
=> Removed unused lines in read_custom_reference_file

input_examples/benchmark_diagnostics_input, input_examples/c2001_case0_input, input_examples/c2001_case1_input, input_examples/j2011_steady_hydro_input, input_examples/j2011_steady_mhd_input, input_examples/main_input_jupiter, input_examples/main_input_sun, src/Physics/Benchmarking.F90, src/Physics/Controls.F90
This commit sets advect_reference_state to true by default.  As discussed in the issues section, this is probably the more intuitive default setting.  Note that with this commit, Rayleigh's internal benchmark routines now explicitly set this variable to false if one of the four benchmark modes are activated.   All input files have this variable set to false for consistency with the old default value that they assumed.
=> Advect ref

post_processing/rayleigh_diagnostics.py
Makes doc string (regarding indices) compatible with new doc strings for Point_Probes and Meridional_Slices. Also gives Shell_Slices, Shell_Spectra, SPH_Modes, and Power_Spectrum the alternate property
rad_inds (for compatability with Point_Probes)
identical to 
inds (for backwards compatability). 
There used to only be the property inds.
=> Shell slice and spectra consistency

configure
This should fix an error message displayed if the GNU compiler is used,
but `gfortran` is not a valid compiler. I don't see a downside to this
change because we already make sure `FVERSION` is set to `GNU`.
Fixes #302.
=> fix error in CPU autodetect message

doc/source/User_Guide/io_control.rst
The docs had a wrong quotation mark in the Fortran namelist.
=> fix quotation marks in namelist

CHANGELOG.md, src/Physics/Sphere_Spectral_Space.F90
The benchmarks, as well as most users, run with diffusion coefficients (nu, kappa, eta) that are constant in radius.   Because of this, a bug in the code has gone unnoticed for a very long time.   The diffusive terms are evolved using the semi-implicit Crank-Nicholson method, which is effectively an average of the forward and backward Euler methods.   A magnetic diffusion term for the A-potential equation, namely dA/dr*deta/dr was being evolved without the explicit contribution from the CN scheme (i.e., the forward Euler component).   This PR fixes the issue.
Please do not accept this PR just yet.  I would like to hear from Rene about how we might automatically manage release notes before this is fully accepted.
=> [Critical]  Fix CN implementation of radially varying magnetic diffusion

CHANGELOG.md, src/Physics/PDE_Coefficients.F90
This PR modifies the CFL calculation in Rayleigh to account for the rotation rate.  The timestep may now be no larger than CFLMax/(c1*4), where CFLMax is the CFL safety factor.  c1 is the 1st Rayleigh constant, effectively the inverse of the rotational timescale (c1 = 2 Omega for reference_type=2 and 2/Ek for reference_type=1).
=> CFL Condition:  Account for Rotation Rate

CHANGELOG.md, doc/source/User_Guide/physics.rst, src/Physics/BoundaryConditions.F90
This PR modifies the code so that the user no longer needs to specify dTdr_top when running models with internal heating and fix_dTdr_top set to true.   This process is very error-prone from a user standpoint, and so it is now done automatically.  Any additional flux passing through the lower boundary is also taken into account in the event that fix_dTdr_bottom is set.   The behavior may be overridden by setting adjust_dTdr to false in the Boundary_Conditions namelist.
=> Automatic calculation of dTdr_top for models with internal heating.

INSTALL, configure, doc/source/User_Guide/installation.rst, doc/source/User_Guide/running.rst
This add `configure` support for the Cray compiler (`ftn`) and updates the documentation accordingly.
This should not interfere with any of the other compilers.
=> support for Cray compiler

post_processing/rayleigh_diagnostics.py
This small PR updates the build_file_list routine as follows:
1) A doc string has been added
2) Non-numbered files found by listdir are now ignored (previously these would cause a crash).
3) Logic related to the '_special' suffix has been removed.  This dates back to an older version of this routine I developed for use with ASH data and is irrelevant to Rayleigh's file format.
=> Revised build_file_list routine

doc/source/User_Guide/devel_environment.rst, doc/source/User_Guide/installation.rst, spack-repo/packages/rayleigh/package.py, spack-repo/repo.yaml
This adds a spack repository with a package for Rayleigh and the corresponding documentation. It's quite useful for building Rayleigh in HPC environments because it takes care of building all the dependencies with the right compiler, MPI etc. It can also be used to provide Rayleigh as a module to share with other users.
=> add a spack package

doc/source/User_Guide/physics.rst, examples/custom_thermal_profile/custom_thermal_profile.ipynb, src/Physics/Initial_Conditions.F90
This commit adds functionality.   Rayleigh already possesses an initial condition option to specify a conductive entropy/temperature profile + random thermal perturbations.  This commit extends that functionality to allow a user-specified ell=0 profile to be used instead.   Documentation and an example notebook are included.    This is accomplished via the generic input interface, so I would suggest Cian review this.
=> Custom Initial Entropy Profile

environment.yml
It turns out that the failure in the CI pipeline was due to a change in the conda `mpich` package and not in our `configure` script. The `mpif90`/`mpifort` wrapper script injects the `-fallow-argument-mismatch` option, probably to work around issues with some versions of MPICH. As the script doesn't check of the compiler is new enough to actually provide that options we get the error. I've bumped the version of the `compilers` package to fix this. We are now using gfortran 10.3.0. I don't think this should break anything else in Rayleigh.
=> switch to newer conda compilers to fix CI

src/Math_Layer/Chebyshev_Polynomials.F90
The Cray compiler (cce) is giving an error because we are mentioning the undeclared variable `nthr` in the `OMP PARALLEL` clause. It isn't being using if `useomp` is not set in the preprocessor, which is probably why we haven't seen problems with the other compilers. I see several ways to fix this. Which is the best depends on our handling of OpenMP, which I don't know much about.
1. Declare `nthr` and set it in both parts of the `#ifdef useomp`. Actually we can use one consistent definition of `kstart` and `kend` here, which makes the code cleaner in my opinion. _This is what I implemented in this PR so far._
2. Remove `nthr` altogether and call `omp_get_num_threads()` twice to the the number of threads. These calls should be very cheap.
3. Define `nthr` locally within a Fortran `BLOCK`. …
=> fix use of undeclared variable in OMP PARALLLEL clause

doc/source/User_Guide/index.rst, index.rst
This is a suggestion for how to reduce the number of top-level sections in the documentation. I think all three of these are really sub-parts of the user guide. I am not entirely sure where to put them, but we can easily reorder the sections in the user guide. If you want me to put them in a different place I can move them around.
=> Move some documentation sections into the user guide

post_processing/plot_G_Avgs.py
This resizes the array on the fly to support G_Avg files with a variable number of iterations per files.
fixes #375
=> allow plot_G_Avgs.py to parse files with variable number of iterations

.github/workflows/docker.yml
This adds a github action workflow to automatically create a docker image of Rayleigh when:
1. A PR is merged into master. A new docker image with the tag geodynamics/rayleigh:latest is generated.
2. A Rayleigh release is generated. A new docker image with the tag geodynamics/rayleigh:RELEASE_TAG is generated (where RELEASE_TAG is replaced by the tag of the release used by github).
The image that is generated itself is a bit outdated at the moment (it is based on the tester container using Ubuntu 18.04), but the workflow will use the Dockerfile in docker/rayleigh to build the image, so updating the Dockerfile will automatically update the docker image.
=> Add workflow that creates a docker container of Rayleigh

configure
Debian and Ubuntu had the `intel-mkl` package for several years now, which provides a full MKL install as part of the normal package repository. This flag makes it easy to use this MKL install. Just setting `MKLROOT` doesn't work unfortunately because the paths can't be made to match for libraries and includes.
=> add configure option to use MKL provided by Debian/Ubuntu

docker/rayleigh-buildenv-jammy/Dockerfile, docker/rayleigh-buildenv-jammy/README.md, docker/rayleigh-devel-jammy/Dockerfile, docker/rayleigh-devel-jammy/entrypoint.sh
This creates a new buildenv container using the most recent LTS version of Ubuntu. As packages got updated since Ubuntu Bionic, we can now build Rayleigh and the documentation without relying on pip, except for `nbstripout`, which still does not have a package. This also switches from the standard LAPACK and FFTW to the MKL versions, which are available in the Ubuntu repository.
Other small changes:
- Using `apt-get` instead of `apt` to avoid the warning about the unstable command-line interface
- Remove the repository lists after package install to keep the container size down.
=> new buildenv using Ubuntu Jammy

conf.py
This PR fixes #353 by disabling the execution of jupyter notebooks when the documentation is build on readthedocs. We can later figure out a fancy way of getting the necessary data to readthedocs, but for now this is the simplest way to remove the error messages in the documentation.
=> Disable execution of jupyter notebook on readthedocs

post_processing/plot_Equatorial_Slices.py, post_processing/plot_Shell_Slices.py, post_processing/rayleigh_diagnostics.py
Changed plot_Shell_Slices.py to make Mollweide plots
=> Use Mollweide Projection for Shell Slices

.github/workflows/main.yml
This makes use of #391 to simplify some of the mpirun options, which can now be handled by environment variables. Also change the trigger action for the workflow to avoid running the workflow when users push random branches to their personal forks (= waste of energy).
=> Update test workflow

docker-devel, docker-devel.bat, docker/rayleigh/Dockerfile
This updates all containers to the new Ubuntu Jammy base. Before we merge this the corresponding base containers (`rayleigh-buildenv-jammy`, `rayleigh-devel-jammy`) should be pushed to the `geodynamics` namespace on Docker Hub.
This also exposes port 8888 so that Jupyter notebooks can be accessed from outside the container with a command like:
```sh
docker run -it --rm -p 8888:8888 geodynamics/rayleigh
jupyter notebook --ip=\*
```
=> Update containers available to users

conf.py
This fixes a little quirk in the current documentation. The CIG logo is only displayed correctly on the homepage, because it is inserted as static html code to every page. On subpages the path is currently not correct.
In order for this to work the path needs to be absolute to the homepage, not relative to the current page.
=> Fix path to CIG logo on subpages of documentation.

doc/source/User_Guide/getting_started.rst, doc/source/User_Guide/index.rst
This PR changes:
- Adds installation instructions for Stampede2 (I think we should move out all the installation details from Getting Started into a separate Installation section, but that would be something for later).
- Changes User Manual to User Guide (I thought we had settled on User Guide?)
- Removes leftovers from the manual reorganization in index.rst.
=> Add installation instructions for Stampede2.

.readthedocs.yaml
Please don't merge this yet.
When building our documentation, we seem to be hitting a memory limit at Readthedocs.   They suggest switching to mamba.  This PR is a first attempt at this.
=> WIP:  Switching from conda to mamba for Readthedocs build

src/Physics/PDE_Coefficients.F90
This small but important bug fix addresses an array-bounds issue that arose as part of the multiple-scalar fields addition.  The ra_constants array is now initialized to be max_ra_constants in size.  The augment_reference routine expected that array to be n_ra_constants in size, however, resulting in a seg fault.  This PR fixes the issue.  I would like for @cianwilson to review this PR if time allows.
=> Bug Fix: Augment_Reference

src/Physics/PDE_Coefficients.F90
The restore_reference_defaults routine was incorrectly setting the default value of angular_velocity to 1.0 instead of -1.0.  This creates a logical error when running benchmark mode alongside a custom reference state.  The result is that the angular_velocity variable is set to 2, regardless of what is specified in the custom_reference file.   Benchmarking mode is intended to work with custom reference states, in part so that this functionality can be validated against known solutions.  The one-line change in PDE_Coefficients.F90 fixes this issue.
=> BUG FIX: Restore_Reference_Defaults and Angular_Velocity

src/Physics/PDE_Coefficients.F90
This PR adds the ability for the user to modify the background dSdr and dTdr through the augment_reference routine.  This functionality has been added to allow advection of a background temperature gradient in a Boussinesq model without the need to specify a full custom reference state.   I've added this at the request of @jorafb , so I am assigning the review of this PR to him.
=> Adding Custom Background dSdr and dTdr via augment_reference.

src/Physics/PDE_Coefficients.F90
The Restore_Reference_Defaults() routine of PDE_Coefficients was a bit out of date. Some variables were not restored to their proper values, or at all. Not all the allocatable arrays were deallocated. This pull request should fix these errors. It incorporates the code cleanup from my other pull request (#426 ).
=> Fix errors in Restore_Reference_Defaults() subroutine

src/Physics/PDE_Coefficients.F90
There was an issue in the logic for specifying custom scalar diffusions. Only nu_type, kappa_type, and eta_type were checked to be 3, with the result that if custom scalar diffusions were used, they might not be read from the binary file (unless reference_type was 4, in which case, the custom reference file had already been read). 
Similarly, for reference_type != 4 there was an indexing issue in temp_constants, that led to seg faults if one of the reference_types was 3. @feathern perhaps this is related to the issues you were seeing regarding custom reference and the scalar fields? 
Anyway, this pull request should fix these bugs. It incorporates my other pull requests (#427 and #426). 
Finally, there is an outstanding issue (that is supported by my preliminary testing) with custom …
=> Fix bugs for custom diffusions

src/Physics/PDE_Coefficients.F90
Adds loops to Constant_Reference(), Polytropic_ReferenceND(), and Polytropic_Reference() to initialize the previously zeroed-out active-scalar buoyancy constants.
=> Initialize scalar buoyancy coeffs2

src/Physics/PDE_Coefficients.F90
This pull request "safeguards" the diffusion coefficients part of the equation_coefficients file. It adds the new subroutine Set_Diffusivity_Equation_Coefficients(), called at the end of Initialize_Transport_Coefficients(), to ensure that equation_coefficients always reflects what the code actually solved, at least for the diffusion pieces. 
This should fix the bug mentioned in #433 and guard against similar possible bugs in the future.
=> Fix equation coefficients custom diffusions

doc/source/User_Guide/getting_started.rst, job_scripts/NASA_Pleiades/pleiades_script.sh, job_scripts/NASA_Pleiades/pscript_bro, job_scripts/TACC_Stampede2/stampede2_jobscript.sh
This PR adds instructions for compilation on the NASA Pleiades system.  It also adds a Rayleigh/job_scripts directory with subdirectories for Stampede2 and Pleiades, each of which contains a sample jobscript along with commands needed to compile the code.    That way, everything is easily accessible once the repository is cloned.  I removed the TACC jobscript from the main documentation to streamline things and avoid too much duplication of information.  I think the installation instructions are useful to retain, even if they're summarized in the jobscripts.
Happy to iterate on this, change directory names etc.
=> Updated HPC Installation Section

doc/source/accessing_and_sharing_data.rst
Add the INCITE dataset to the list of accessible Rayleigh data. We are in the process of finishing up the website allowing access to that data. A probably final version (not yet merged) can be seen here: https://incite--13.org.readthedocs.build/en/13/.
=> Add a link to the INCITE dataset.

post_processing/rayleigh.py
This should fix the CI issues we had. It's probably due to a change in the way `black` formats things. For the record, you can just run `black rayleigh.py` and commit the changes to fix the issue.
=> remove newline to remove black linter warnings

src/Physics/Benchmarking.F90
There is a logical issue in Benchmarking.F90 that is causing the name of the custom reference file (and also heating_type) to be lost when with_custom_reference is true but no benchmarking mode is active.  This PR fixes the logic.
=> Bug Fix: Custom reference filename being reset

.github/workflows/main.yml, doc/source/User_Guide/getting_started.rst
Our current conda environment seems to fail to resolve on linux machines. It works if I remove pandoc from the environment file. Conda will still be pulled in implicitly, but with a version that seems to satisfy requirements more easily. I can still build the documentation locally, let's see what the online tester says.
=> Fix conda environment installation

doc/source/User_Guide/getting_started.rst, docker-devel
This makes the docker-devel script aware of podman and automatically selects it as a fallback. The bat file is not updated as there is no podman on Windows.
=> add support for podman

environment.yml, environment_doc.yml
This PR updates the version of scipy specified by the conda environment files.   The FFT interface has changed since 1.6 and was creating conflicts with an upcoming PR.
=> Updated scipy to version 1.10 (from 1.6).

.github/workflows/main.yml
I noticed that our CI does store the diff between expected and actual test results, but it never uploads them to the github page. This change makes it so that users can download the diff file to investigate exactly what went wrong in the test.
=> Report the diff between expected and actual test report

input_examples/main_input_mhd_jones_FD, src/Makefile.fdeps, src/Math_Layer/Linear_Solve.F90, src/Physics/Controls.F90, src/Physics/Input.F90, src/Physics/ProblemSize.F90, src/Physics/Run_Parameters.F90, src/Physics/Sphere_Driver.F90, src/Physics/Sphere_Linear_Terms.F90, src/Physics/Sphere_Physical_Space.F90, src/Physics/Sphere_Spectral_Space.F90, tests/unit_tests/SHT/expected_output.out
Added all the necessary changes required to run the benchmarks on uniform FD grids when `dr_input` is not specified. When `dr_input` is specified using Fortran-based syntax in the main_input file, Rayleigh can be run with a non-uniform grid. Currently, when the `chebyshev` flag is set to false, finite-difference is activated.
=> Implementation of Finite-Difference formulation

src/Math_Layer/Linear_Solve.F90, src/Physics/Initial_Conditions.F90
The default initial conditions type in Rayleigh allow reading from a checkpoint file (init_type = -1 for thermal and velocity fields, magnetic_init_type = -2 for magnetic fields). Modifications made in this request allow for new IC's:
1.  init_type = -2 reads checkpoint file as well as a user-supplied entropy profile. The sum total of these two is the new IC. 
2. magnetic_init_type = -2 reads checkpoint file and user-supplied profiles of toroidal and poloidal field components. The sum total of checkpoint file and user-supplied profiles is the new IC. 
An additional subroutine Get_RHS is added to src/Math_Layer/Linear_Solve.F90.
=> Initial conditions using checkpoint files added to user supplied files

.github/workflows/main.yml, configure, src/IO/Parallel_IO.F90, src/IO/Spherical_IO.F90, src/Parallel_Framework/All_to_All.F90, src/Parallel_Framework/General_MPI.F90, src/Parallel_Framework/ISendReceive.F90, src/Parallel_Framework/Parallel_Framework.F90, src/Parallel_Framework/Ra_MPI_Base.F90, src/Parallel_Framework/SendReceive.F90, src/Physics/Benchmarking.F90, src/Physics/Checkpointing.F90, src/Physics/Generic_Input.F90
This PR add the new option `--mpi-f08` to `configure`, which bases all of Rayleigh's MPI calls on the `mpi_f08` module instead of the `mpi` module. The default (`mpi`) is left untouched but the hope is that the new option helps us work around many compiler warnings and errors due to stricter type checking. In the long term we probably have switch to `mpi_f08` as this is what the MPI standard highly recommends and the old `mpi` module might go away at some point.
Ideally we should have the CI build and test all MPI variants. I don't want to replicate all the code in the Github actions though. If anyone knows of a more elegant way of running the same code with different `configure` parameters, I'd appreciate it.
Rationale for adding this:
- `mpi_f08` is the only standard compliant way to …
=> Provide support for the mpi_f08 module

post_processing/rayleigh_diagnostics.py
With this PR, the plot_azav routine now returns the img object.  This allows the user to specify the colorbar properties outside of plot_azav if desired.  Previously, there was no return statement, and so the image object needed by the colorbar routine was inaccessible.
=> Added return statement to the plot_azav routine.

post_processing/rayleigh_diagnostics.py
This PR modifies the AZ_Avgs class so that it also accepts a list of multiple AZ_Avgs files. That data can either be concatenated or time-averaged as described in docstring. In addition, the class now contains an output method so that the current AZ_Avgs object structure can be saved to a new AZ_Avgs file.
Some notes:
1) Single files can still be read as they always have been.
2) This is a lot of new code. I've been using this new version of the AZ_Avgs class for a couple of years now. When doing a review, the most straightforward path is probably to test out the concatenation and time-averaging functionality.
=> Updated AZ_Avgs class to allow concatenation and time-averaging.

post_processing/reference_tools.py, src/Physics/PDE_Coefficients.F90
Pull request #489 inadvertently broke the equation_coefficients file, and how it is interpreted by post_processing/rayleigh_diagnostics. I should have updated the version number from 1-->2 since I changed the number of constants from 10 to 11. 
This pull request updates the version number, and also the rayleigh_diagnostics class to read in the equation_coefficients file. I verified it still works on old version=1 equation_coefficients files. 
This pull request additionally addresses issue #491, since in version 2, "nconst" and "nfunc" are explicitly written into equation_coefficients.
=> Fix eqcoeff version number

doc/source/User_Guide/getting_started.rst, docker/rayleigh/Dockerfile
Our current docker container `geodynamics/rayleigh` includes a user with limited permissions and a home directory that is only readable by that user. This is a problem if the container is run using `singularity` or `apptainer`, because these container systems automatically set the user identity inside the container to the user on the outside. This means the Rayleigh installation in the current container is not usable when using apptainer or singularity. A common solution to this problem is to have the docker container default to the root user.
This way the two use cases (docker / apptainer) both work:
- for docker the user id switched to root inside the container and allows everything, including to install new software if necessary (=better than the current container)
- for …
=> Fix geodynamics/rayleigh docker image for apptainer

.github/workflows/docker.yml
This PR makes two changes to building the rayleigh docker container:
1. It builds a multi architecture image for amd64 (all usual systems) and arm64 (closer to current Apple systems). Using docker will automatically download the best image for the current system.
2. It pushes the image not just to docker hub, but also to Github Container Registry (ghcr.io). This just provides the image in another location. Docker Hub has been a bit unreliable in the past and we are adding GHCR as back up for CIG packages.
=> Push to ghcr and build for Apple Silicon

post_processing/Diagnostic_Plotting.ipynb
This PR fixes a minor heading-size issue.  In the section of the documentation that describes how to plot output from Rayleigh, the Diagnostics_Plotting.ipynb notebook is displayed on the screen.  The section on plotting global averages had a smaller heading size than the other sections, preventing it from appearing in the index/table of contents displayed in the documentation.
=> Updated header size for "IV. Global Averages"

src/IO/Spherical_IO.F90
This fixes a subtle bug in Rayleigh.  When opening a file for parallel I/O, Rayleigh records the error code.  It was intended that if a nonzero error code was found, so that the file_open variable remained false, no subsequent file operations would be performed.  A check on the file_open variable was missing, however, for everything but the operations related to writing the file header data.   This PR fixes this bug.
I've been emailing with @illorenzo7 and the NASA HECC staff about this already today, so I'm assigning the review to him.
-Nick
p.s.  I also removed a commented line of debugging code.
=> IO Bug Fix

doc/source/User_Guide/getting_started.rst
An empty line is needed for interpreting the code-block correctly.
=> fix rendering of code-block in documentation

.github/workflows/main.yml
This should hopefully fix the conflict between the uploaded results of the different MPI testers. Each MPI tester now uses its own filename for upload. Let's see what the testers say.
=> Fix ci diff file upload

conf.py
Our documentation build kept recursively ingesting the `doc/build` directory, which made everything slow down with every build.
The reason was a missing comma in exclude_patterns. That caused the two adjacent strings to be merged and prevented `doc/build` from being excluded.
Now subsequent builds are instant if nothing has changed.
=> fix recursive doc build

.github/workflows/docker.yml
The Rayleigh automatic docker container build had problems for a while (maybe forever?), because it no longer builds containers with capital letters (like geodynamics/Rayleigh), but instead requires lowercase letter (geodynamics/rayleigh). This PR modifies our automatic build script to create an environment variable (`REPO_NAME_LC`) which contains the lowercase repository name (`rayleigh`) and use that as the docker container name. I tested that it works now on my own repository, see the container images created here: https://hub.docker.com/r/gassmoeller/rayleigh/tags
and here: https://github.com/gassmoeller/Rayleigh/pkgs/container/rayleigh
Once this is merged it will trigger a build run for the official Rayleigh images on
Dockerhub: https://hub.docker.com/r/geodynamics/rayleigh/tags …
=> Fix container push

src/IO/Parallel_IO.F90, src/Physics/Checkpointing.F90
This fixes a bug in Rayleigh where a checkpoint file can appear to be too large if the file existed and was overwritten in a subsequent run with lower resolution.   This PR ensures that the file is deleted before being written to, preventing this bug.
=> Bug Fix:  Checkpoint file size

configure
Rayleigh does not require references to standard c++ libraries in the configure file in order to make directories.
=> removed references to standard c++ libraries

configure
A suggestion for how to simplify the link options in the configure script. This should be carefully tested on systems with:
- Intel compiler + MKL
- GNU compiler without MKL (this worked on my system)
- GNU compiler with MKL through debian apt
- GNU compiler with MKL through conda
- GNU compiler on MacOS with MKL through conda
=> Simplify link flags in configure

.github/workflows/docker.yml, doc/source/User_Guide/getting_started.rst, docker/rayleigh-tacc/Dockerfile, docker/rayleigh-tacc/Readme.md, docker/rayleigh-tacc/build.sh
This is a preliminary PR that can create a docker image that runs on TACC Stampede2. So far I have it  only running on a single node, and unfortunately the image is quite a bit slower. I suspect this is because I have no access to MKL inside the container. I will think about this a bit more.
=> Add TACC docker image

doc/source/User_Guide/physics_math_overview.rst
Equations for W,Z,P, A and C, along with equations for nonlinear terms.
=> Equations solved in Rayleigh

doc/source/User_Guide/getting_started.rst, doc/source/User_Guide/model_setup.rst, doc/source/User_Guide/physics_math_overview.rst, doc/source/User_Guide/run_at_scale.rst, doc/source/User_Guide/run_rayleigh.rst
This fixes some broken internal links and typos. Another major change is the more consistent use of `verbatim` formatting in the text when it relates to code.
=> Random documentation fixes

CHANGELOG.md
This PR updates the changelog through June 20, 2024 10:20 a.m.
=> Changelog updates through June 20 a.m., 2024

doc/source/User_Guide/model_setup.rst
This corrects a small error in the finite-difference portion of the documentation.  The initial example in that section is intended to illustrate how to set up a uniform grid in radius.  Two lines of code were included in that example erroneously, however, which produced a nonuniform grid.
=> Finite-Difference Documentation Bug Fix

.github/workflows/main.yml, configure
Added conditionals so that the user has the correct compiler and libraries configured before the actual configuration is run.
=> Modified Configuration File

CHANGELOG.md, doc/source/User_Guide/arbitrary_scalar_fields.txt, doc/source/User_Guide/physics_math_overview.rst, doc/source/User_Guide/under_development.rst
Also hopefully providing a framework for how we can implement custom reference states for them that I'd like to use as a discussion point.
=> Expanding the documentation on arbitrary scalar fields.

CHANGELOG.md, src/Physics/Checkpointing.F90
This pull request should accomplish two main goals:
1. Allow the user to increase the number of radial points in each Chebyshev sub-domain (even with multiple domains, e.g., ncheby=64, 96 --> ncheby = 96,256) and then restart from a checkpoint with the old (coarse) resolution. Before, the chebyshev coefficients weren't initialized correctly for multiple domains. 
2. Throw an error message and exit if the user tries to lower radial resolution in any subdomain. Before, the code would simply do nothing, likely integrating a bunch of zeros.
=> Allow radial resolution changes for multiple domains

.github/workflows/main.yml, CHANGELOG.md, CMakeLists.txt, cmake/FindFFTW.cmake, cmake/FindMKL.cmake, doc/source/User_Guide/getting_started.rst, environment.yml, src/CMakeLists.txt, src/gen_header.sh
This adds support for building Rayleigh using CMake. It is purely optional and does not interfere with the traditional, `configure`-based approach.
You can try it like this:
```sh
cmake -B build
cmake --build build -j
```
The `rayleigh` executable will be placed in `build/src`.
Todo:
=> add CMake support

doc/source/User_Guide/getting_started.rst
The logic recently changed in the configure file so that the -mkl flag must be passed to configure when using MKL. This is true even when using an Intel compiler with MKLROOT specified in the user's environment. This PR updates the documentation to reflect this change. In addition, it is best practice on Pleiades to load the compiler and mpi module at the same time owing to a bug that occurs on some node types if they are run one after the other. This has nothing to do with Rayleigh, but I've updated the documentation to hopefully help people avoid this bug.
=> Updated Pleiades install instructions.

.github/workflows/main.yml, CHANGELOG.md, doc/source/Namelist_Definitions/boundary_conditions_namelist.txt, doc/source/User_Guide/coupled_bcs.txt, doc/source/User_Guide/under_development.rst, src/IO/Spherical_IO.F90, src/Physics/BoundaryConditions.F90, src/Physics/Sphere_Linear_Terms.F90, tests/coupled_bcs/const/generate_input.py, tests/coupled_bcs/const/main_input, tests/coupled_bcs/run_test.sh, tests/coupled_bcs/test_output.py
This PR allows the boundary values or radial gradients of scalar fields (including the thermal variable and active scalar fields) to be linearly coupled together.
The new functionality is documented in the "Under Development" section of the User Guide.
The most pressing point for review is that this changes the number of boundary condition types from two (Dirichlet and Neumann) to four (Dirichlet, Neumann, coupled Dirichlet and coupled Neumann).  Combined with the fact that, in an effort to not add too many new options, `T_top`, `T_bottom`, `dTdr_top`, `dTdr_bottom`, `chi_a_top`, `chi_a_bottom`, `dchidr_a_top`, `dchidr_a_bottom`, and their `_file` equivalents have been overloaded, this means that the previous defaults (e.g. `fix_Tvar_top=.true.` with `T_top=0`) have had to be taken away. …
=> Allow the boundary conditions of scalar fields to be coupled

doc/source/User_Guide/index.rst, doc/source/User_Guide/spectral_input.txt, doc/source/User_Guide/utilities.rst
This allows for more in-depth, standalone documentation of scripts.
Currently this just includes rayleigh_spectral_input.py but that seems to be in demand.
=> Adding a documentation page for "Utilities"

.github/workflows/main.yml, CHANGELOG.md, Makefile, doc/source/User_Guide/getting_started.rst
At the moment the build just continues on failed documentation builds in the Conda action. That's not very useful and we might as well skip the documentation build. We should check it though to make sure the docs also build on macOS.
This PR makes the action fail on error and splits the documentation build into HTML (`make doc`) and PDF (`make docpdf`) outputs.
=> check the  documentation build in the conda action

CMakeLists.txt, conf.py, doc/CMakeLists.txt
This adds the targets `make doc`, `make doc_html`, and `make_pdf` to the cmake build system. `make doc` builds both of the other targets.
The targets depend on all files in `doc/source` so it is only rebuild if something changes in that directory.
The only change to the existing system that I had to make was the modification to the conf.py that makes the exclude path of `doc/build` independent of the directory it is executed from (otherwise I got the same recursive addition of build files we repaired earlier in the week).
=> Add documentation to the cmake build system

post_processing/reference_tools.py
This fixes #560 and includes some Python cleanup.
A simple script like this (save as `convert.py`) can be used to convert all the `equation_coefficients` files that were written in the inconsistent state:
```python
#!/usr/bin/env python3
import sys
from reference_tools import equation_coefficients
for f in sys.argv[1:]:
e = equation_coefficients(file=f, override_nconst=True)
e.write(f)
```
Run it with `find -name equation_coefficients -exec python3 path/to/convert.py {} +`. Back up your files first.
=> Add option to allow `reference_tools` to load some broken `equation_coefficients` files

post_processing/reference_tools.py
It looks like I somehow forgot to add the radial_grid class to reference_tools.py when I submitted the PR for updates to Rayleigh's finite-difference mode.  This PR adds that class to reference_tools.py.  It's usage is discussed in the documentation [here.](https://rayleigh-documentation.readthedocs.io/en/latest/doc/source/User_Guide/model_setup.html#using-a-grid-description-file-to-specify-a-nonuniform-grid)
I'm tagging @rpvin , since he noticed this was missing.
=> Add radial_grid class to reference_tools.py.

src/Physics/Controls.F90, src/Physics/PDE_Coefficients.F90, src/Physics/Sphere_Hybrid_Space.F90, src/Physics/Sphere_Linear_Terms.F90, src/Physics/Sphere_Physical_Space.F90
Added the capability to switch from anelastic to the pseudo-incompressible approximation.  With pseudo-incompressibility turned off, it has run the hydro anelastic benchmark on Pleiades without throwing errors, but it ran incredible slow.  Made as a draft pull to allow other developers to check the implementation.
=> [wip] Simplified and minimal update to include pseudo-incompressibility

CHANGELOG.md, src/Diagnostics/Diagnostics_Second_Derivatives.F90, src/Makefile.fdeps
This fixes a bug related to finite-difference mode.  When diagnostic output quantities are requested that require a second radial derivative, that derivative is calculated at output time.  The subroutine that handles the derivative calculations at output time was lacking any logic that would call the appropriate finite-difference derivative routine.  Instead, a Chebyshev derivative routine was called, which caused a crash because the Chebyshev grid object had not been initialized.  This PR fixes this bug by adding appropriate finite-difference logic to Diagnostics_Second_Derivatives.F90.
=> Bug Fix:  Diagnostics and Second Radial Derivatives when Using Finite-Difference Mode

doc/source/Namelist_Definitions/temporal_controls_namelist.txt, doc/source/User_Guide/run_rayleigh.rst, src/Physics/Checkpointing.F90, src/Physics/Controls.F90
This PR adds the checkpoint_minutes variable to the temporal_controls namelist.  Similarly to the quicksave_minutes variable, this can be used as an alternative to specifying the number of timesteps between adjacent checkpoints.
I've also updated the documentation to reflect this change.
I'm tagging @jorafb on this as a potential reviewer.
=> Checkpointing interval can now be specified in minutes.

src/Diagnostics/Diagnostics_Base.F90, src/Diagnostics/Diagnostics_Custom.F90, src/Diagnostics/Diagnostics_Interface.F90, src/Diagnostics/Diagnostics_Mean_Correction.F90, src/Diagnostics/Diagnostics_Miscellaneous.F90, src/Diagnostics/Diagnostics_Second_Derivatives.F90, src/Diagnostics/Diagnostics_TurbKE_Budget.F90, src/IO/Spherical_IO.F90, src/Makefile.fdeps, src/Math_Layer/Chebyshev_Polynomials.F90, src/Math_Layer/Finite_Difference.F90, src/Math_Layer/Fourier_Transform.F90, src/Math_Layer/Legendre_Polynomials.F90, src/Math_Layer/Legendre_Transforms.F90, src/Math_Layer/Linear_Solve.F90, src/Parallel_Framework/MPI_LAYER.F90, src/Parallel_Framework/Parallel_Framework.F90, src/Parallel_Framework/SendReceive.F90, src/Parallel_Framework/Spherical_Buffer.F90, src/Physics/Benchmarking.F90, src/Physics/Checkpointing.F90, src/Physics/Controls.F90, src/Physics/Fields.F90, src/Physics/Generic_Input.F90, src/Physics/Initial_Conditions.F90, src/Physics/PDE_Coefficients.F90, src/Physics/Sphere_Linear_Terms.F90, src/Physics/Sphere_Physical_Space.F90, src/Physics/Sphere_Spectral_Space.F90
This PR removes all calls to write(6,\*) in the code that can be encountered during the course of a normal simulation.   Instead, stdout%print is used, which is redirected to a log file, if desired.    This change prevents a situation where some error message could be written out to standard out, whereas others would appear in the log file.   Note that several references to write(6,\*) have been retained.  These are not encountered during normal usage of the code and can still be helpful for debugging.  In addition, many references to write(6,\*) which were commented out or unnecessary have been removed.  This PR fixes issue #325 .
=> Removal of Write(6,*)

src/IO/Spherical_IO.F90
This PR implements some consistency/sanity checks when Rayleigh interprets the values of variables such as shellslice_levels, meridional_indices etc.  Previously, Rayleigh would accept values that fell outside of the grid bounds, which could lead to crashes.  With this addition, indicial values that fall outside of the grid bounds are filtered out.   If unallowed values are specified for the normalized indices (e.g., shell_slice_levels_nrm), those should also be filtered out by these modifications to the code logic.
This addresses the cause of the 2nd crash reported in issue #570.
=> Consistency Check for Indexed Outputs (e.g., Shell_Slices, Meridional_Slices)

src/Makefile.fdeps, src/Physics/PDE_Coefficients.F90
This PR should fix the finite-difference part of issue #570 reported by @rpvin . Please try this out when you get a chance to see if initialization now works properly for custom reference states with FD turned on.
=> Added finite-difference support to the log_deriv subroutine.
